### ISSUE TITLE
Deriving from DelegateCommand<T> and overriding the Execute method does not result in it being executed when the command runs

### ISSUE THREAD

**Issue by nickkazepis** [PrismLibrary/Prism#732] opened 2016-08-19 11:14 UTC
### Package info

- Platform: Windows 7 Pro x64
- Prism version: nuget package 6.1.0
- Xamarin version (if applicable):
- Windows 10 SDK version (if applicable):
- Other version info: .NET 4.5

### Repro steps
Just derive a templated class from DelegateCommand<T> e.g. public MyClass<T> : DelegateCommand<T>{}

override the Execute(T parameter) method

Declare an ICommand property and point it to the derived MyClass<T> command

Bind a button from XAML to the ICommand property

add a breakpoint inside the overridden method and execute...

**Comment by dvorn** [comment] 2016-08-19 15:03
@brianlagunas I prepared a fix, but may be that was the design?  Although I cannot imagine the purpose of such design...

**Comment by dvorn** [comment] 2016-08-19 15:05
@nickkazepis As a temporary fix you may override the method

`protected override Execute(object parameter)`

Note the difference in the type of the parameter.

**Comment by brianlagunas** [comment] 2016-08-19 16:47
I'll have to look into this.  The DelegateCommand was originally created by Microsoft, and it has been this way since it's creation, so I am hesitant to change it.  I will see if I can find out the thinking behind why they did it the way they did.  If anything, I think you should be deriving from DelagateCommandBase.

**Comment by dvorn** [comment] 2016-08-19 17:26
This is the story: http://compositewpf.codeplex.com/workitem/8101

Initially (v4) DelegateCommand.Execute was supposed to only be called programmatically, not by WPF.

Then (v5) they thought they made it extendable by making it virtual.  

Now I think this is a bug.

**Comment by brianlagunas** [comment] 2016-08-19 17:37
Right!  Hmmm.... not sure how to take this one.  We can't remove the virtual, because I'm sure there is someone extending the DelegateCommand by overriding this method as-is.  Maybe just leave this as by design and call it done.

**Comment by dvorn** [comment] 2016-08-19 17:41
If someone override it, it will work only when the command is called programmatically.  It will not work for typical binding scenarios.  E.g., someone added logging...  What's the use of logging if it works in test but does not work in real program?

**Comment by brianlagunas** [comment] 2016-08-19 17:48
I almost want to completely rewrite the DelegateCommand, because it seems too overly complicated to me.  They even mixed Async verison in the same delegate command, but required the use of a static factory method to create it.  I would prefer to have a DelegateCommandAsync or something instead, and simplify the current DelegateCommand.

**Comment by brianlagunas** [comment] 2016-08-19 23:06
I'm closing this as "by design" since this was the decision by the original authors of Prism.  I will talk with @briannoyes about what to do here.

**Closed by brianlagunas** 2016-08-19 23:06 UTC

**Comment by dvorn** [comment] 2016-08-20 03:49
It was "by design" in v4, but in v5 they made an explicit attempt to make DelegateCommand extendable [What's New in Prism Library 5.0 for WPF](https://msdn.microsoft.com/en-us/library/gg430871(v=pandp.40).aspx):

> CodePlex Issues Resolved
8101: DelegateCommand is not extendable.

**Comment by dvorn** [comment] 2016-08-20 03:50
Added a fix for non-generic DelegateCommand

**Comment by nickkazepis** [comment] 2016-08-25 08:24
Sorry for mu absence the last few days, I didn't have access to the internet.
The initial idea behind deriving from delegate command was for logging.
I wanted to create a derived class so that I could perform some reflection to acquire the caller's name for logging purposes. I overrode the 
```
Execute(object parameter) 
```
as @dvorn said but I ended up at a dead-end because of the way the constructor encapsulates the argument into an anonymous lambda during base initialization
```
: base((o) => executeMethod((T)o), (o) => canExecuteMethod((T)o))
```
so that the caller was always the constructor. Since i didn't want to play with the StackFrames (not very safe) I ended up deriving from delegate command and doing something similar when passing the constructor arguments to the base, injecting some logging logic which in turn gets re-encapsulated by the aforementioned base constructor anonymous lambda. I just wanted to share the actual use case scenario in case it helps.

**Comment by dvorn** [comment] 2016-08-25 08:40
@nickkazepis There is another issue related to DelegateCommand under discussion: #724.  
@brianlagunas If you ever going to change the DelegateCommand implementation, a fix for this issue may also be included.

**Comment by dvorn** [comment] 2016-08-25 08:56
@nickkazepis Try this:

```csharp
public MyCommand : DelegateCommand<T>, ICommand
{
    async void ICommand.Execute(object parameter)
    {
        Log(...);
        await Execute(parameter);
    }
}
```

**Comment by joelweiss** [comment] 2016-09-28 22:45
For anyone who runs into this issue, the same is when you override `CanExecute()` you must override the `CanExecute(object parameter)`
