### ISSUE TITLE
The ObservesProperty() on the DelegateCommand does not listen for property change on an capsulated object

### ISSUE THREAD

**Issue by CrestApps** [PrismLibrary/Prism#1415] opened 2018-04-04 23:18 UTC
### Description
I am trying to use `IInteractionRequestAware` to display a dialog where the user will type in her/his age. The dialg has a "Continue" button, this button should only be enabled if the user selected a birthday that makes her/him 18+ years old.

### Steps to Reproduce

I have a view model called `CaptureCustomerAgeViewModel` which implements the `IInteractionRequestAware`.
```
    public class CaptureCustomerAgeViewModel : ObservableConfirmation, IInteractionRequestAware
    {
    	public DelegateCommand CloseDialog { get; set; }
        public Action FinishInteraction { get; set; }
        private ConfirmCustomerAge CapturedAge { get; set; }
        public INotification Notification
        {
            get
            {
                return CapturedAge;
            }
            set
            {
                var val = value as ConfirmCustomerAge;
                if (val != null)
                {
                    CapturedAge = val;
                    RaisePropertyChanged();
                }
            }
        }

        public CaptureCustomerAgeViewModel()
        {
            CloseDialog = new DelegateCommand(HandleCloseDialog, IsQualified).ObservesProperty(() => CapturedAge.BirthDate);
        }

        private bool IsQualified()
        {
            return CapturedAge != null
                && CapturedAge.BirthDate.HasValue
                && CapturedAge.BirthDate.Value < DateTime.Now.AddYears(MinYears * -1).Date;
        }

        private void HandleCloseDialog()
        {
            CapturedAge.Confirmed = true;
            FinishInteraction();
        }

        public int MinYears
        {
            get
            {
                return 18;
            }
        }

        public DateTime MinBirthDate
        {
            get
            {
                return DateTime.Now.AddYears(MinYears * -1);
            }
        }
    }
```

Then I have the following view which binds to the previous class

```
<UserControl x:Class="Modules.Register.Views.CaptureCustomerAgeView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:prism="http://prismlibrary.com/"
             prism:ViewModelLocator.AutoWireViewModel="True"
             xmlns:local="clr-namespace:Modules.Register.Views"
             mc:Ignorable="d"
             d:DesignHeight="300"
             d:DesignWidth="300"
             MinHeight="350"
             Width="375">
    <StackPanel>

        <Grid Margin="20">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="2*"/>
                <ColumnDefinition Width="*" />
            </Grid.ColumnDefinitions>

            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
                <RowDefinition Height="3" />
                <RowDefinition Height="Auto" />
                <RowDefinition Height="3" />
                <RowDefinition Height="Auto" />
                <RowDefinition Height="3" />
                <RowDefinition Height="Auto" />
                <RowDefinition Height="3" />
                <RowDefinition Height="Auto" />
                <RowDefinition Height="3" />
            </Grid.RowDefinitions>

            <TextBlock Text="Minimum Age Required"
                   Grid.Column="0"
                   Grid.Row="2"
                   VerticalAlignment="Center"
                   HorizontalAlignment="Right"
                   Padding="0 0 7 0" />

            <TextBlock Grid.Column="1"
                       Grid.Row="2"
                       HorizontalAlignment="Stretch"
                       Text="{Binding MinYears}" />


            <TextBlock Text="Legal Age Birthdate"
                       Grid.Column="0"
                       Grid.Row="4"
                       VerticalAlignment="Center"
                       HorizontalAlignment="Right"
                       Padding="0 0 7 0" />

            <TextBlock Grid.Column="1"
                       Grid.Row="4"
                       HorizontalAlignment="Stretch"
                       Text="{Binding MinBirthDate, StringFormat='dd/MM/yyyy'}" />
            
            <Label Content="Birth Of Date"
                   Grid.Column="0"
                   Grid.Row="6"
                   VerticalAlignment="Center"
                   HorizontalAlignment="Right"
                   Padding="0 0 7 0" />

            <DatePicker Grid.Column="1"
                        Grid.Row="6"
                        HorizontalAlignment="Stretch"
                        SelectedDate="{Binding Notification.BirthDate, Mode=TwoWay, ValidatesOnDataErrors=True, StringFormat='dd/MM/yyyy'}"
                        DisplayDateEnd="{Binding MinBirthDate, Mode=OneWay}" />

            <StackPanel Orientation="Horizontal"
                        Grid.Column="0"
                        Grid.ColumnSpan="2"
                        Grid.Row="8"
                        HorizontalAlignment="Center"
                        Margin="10 30">
                
                <Button Content="Continue"
                        Command="{Binding CloseDialog}"/>

            </StackPanel>
            
        </Grid>
    </StackPanel>
</UserControl>
```

Finally, the class `ConfirmCustomerAge` look like this
```
    public class ConfirmCustomerAge : ObservableConfirmation
    {
        [Required]
        public DateTime? BirthDate { get; set; }
    }
```

The `ObservableConfirmation` class simple implements the `Confirmation, INotifyPropertyChanged, IDataErrorInfo`

I am also using `Fody.PropertyChanged 2.4.0` to inject the `RaisePropertyChanged()` at compile time.

If I remove the `IsQualified()` method from `DelegateCommand()` everything will work as expected and the age is passed back correctly. But the problem is that I can't let the user execute the `CloseDialog` command unless he/she `IsQualified()`.

### Expected Behavior
Since, I am using `ObservesProperty(() => CapturedAge.BirthDate)` I am expecting the `IsQualified()` method to get called when the user selects a date or the `DatePicker` loses focus.

### Actual Behavior
When I selects a date, the "Continue" button will stay disabled. In fact, the `IsQualified()` method is only called when the ViewModel class is constructed.

### Basic Information

- Version with issue: 6.3.0.0

### Screenshots
First screen shot show the dialog when the view model is first constructed.

![screenshot_1](https://user-images.githubusercontent.com/24724371/38339555-9d52dac2-3823-11e8-895d-058e7311f6c7.png)

Second screenshot show after the date is selected, the button stay disabled.
![screenshot_2](https://user-images.githubusercontent.com/24724371/38339556-9d6fa512-3823-11e8-85b1-dc87b9616b69.png)

**Comment by brianlagunas** [comment] 2018-04-05 00:09
Closing this issue because the reproduction link has not been provided (the issue template labels this as required).  The main thing to verify is that INPC for the BirthDate is being executed.  My recommendation would be to call INPC manually and see if the behavior changes.

**Closed by brianlagunas** 2018-04-05 00:09 UTC

**Comment by CrestApps** [comment] 2018-04-05 00:47
This is a WPF app. I am not sure how to create a reproduction link to demonstrate the issue. What is INPC and how can I verify it?

**Comment by brianlagunas** [comment] 2018-04-05 00:51
Create a blank WPF app, add the minimal code to reproduce the issue, upload it to your github and provide the link to the repo.  INPC = INotifyPropertyChanged

**Comment by CrestApps** [comment] 2018-04-07 15:41
@brianlagunas I created the requested reproduction link https://github.com/CrestApps/InteractionRequestTrigger

In that project I did not use Fody.PropertyChanged. Instead, I manually called the [RaisePropertyChanged](https://github.com/CrestApps/InteractionRequestTrigger/blob/master/InteractionRequestTrigger/ConfirmCustomerAge.cs#L19) method.

When the application run, click the button on the MainWindow.

When the dialog comeup, please select a any available date, I am expecting the "Qualified" button to become enabled but for some reason it isn't.

I hope this makes it easy for you to troubleshoot the problem.

**Comment by CrestApps** [comment] 2018-04-07 18:49
I tried to trace the code to see if I can help in the debug.

The issue seems to be in the `DelegateCommandBase` class specifically in the `void HookInpc(MemberExpression expression)` method



        protected void HookInpc(MemberExpression expression)
        {
            if (expression == null)
                return;

            if (_inpc == null)
            {
                var constantExpression = expression.Expression as ConstantExpression;
                if (constantExpression != null)
                {
                    _inpc = constantExpression.Value as INotifyPropertyChanged;
                    if (_inpc != null)
                        _inpc.PropertyChanged += Inpc_PropertyChanged;
                }
            }
        }


The `expression.Expression as ConstantExpression` line returns null which is why the `_inpc.PropertyChanged` isn't called on the property.

**Comment by brianlagunas** [comment] 2018-04-08 21:52
First off, your `CapturedAge` property is private. This won't work, it must be public.  Secondly, your `CapturedAge` isn't calling INPC, so once again this won't work.  Fix your `CapturedAge` property:

```
        private ConfirmCustomerAge _capturedAge;
        public ConfirmCustomerAge CapturedAge
        {
            get => _capturedAge;
            set
            {
                _capturedAge = value;
                RaisePropertyChanged();
            }
        }
```

While you're at it fix your `BirthDate` property too.
```
        private DateTime? _birthDate;
        [Required]
        public DateTime? BirthDate
        {
            get
            {
                return _birthDate;
            }
            set
            {
                _birthDate = value;
                RaisePropertyChanged();
            }
        }
```

**Comment by CrestApps** [comment] 2018-04-08 23:27
Updated the code but still same issue. https://github.com/CrestApps/InteractionRequestTrigger/blob/master/InteractionRequestTrigger/ConfirmCustomerAge.cs 

Please have a look at my above note regarding [HookInpc(MemberExpression expression)](https://github.com/PrismLibrary/Prism/issues/1415#issuecomment-379490793)

When I am observing the following `ObservesProperty(() => CapturedAge.BirthDate)` the `expression.Expression` will not get casted to `ConstantExpression`

**Comment by CrestApps** [comment] 2018-04-09 14:50
I see. I actually upgraded to the latest stable (i.e. 7.0.0.396) and it seems to be working fine. I also tried it on `7.1.0.123-pre` and it works too.

**Comment by CrestApps** [comment] 2018-04-09 15:02
The class [UnityBootstrapper](https://github.com/PrismLibrary/Prism/blob/5ae343625f2d63d4f8706bdfa9d805f2095390bf/Source/Wpf/Prism.Unity.Wpf/Legacy/UnityBootstrapper.cs) is decorated with ` [Obsolete("It is recommended to use the new PrismApplication as the app's base class. This will require updating the App.xaml and App.xaml.cs files.", false)]`  but I can't seems to find the `PrismApplication` is there a document somewhere I can read on how to implement the change in my code? Where is the `PrismApplication` class and how should I implement it?
