### ISSUE TITLE
System.ArgumentOutOfRangeException in GoBackAsync method

### ISSUE THREAD

**Issue by mo-kml** [PrismLibrary/Prism#1146] opened 2017-08-27 12:10 UTC
hi there
when i use navigationPage i get this error in GoBackAsync method.but if i remove the navigationPage and navigate my self i wound get this error and my app works perfectly.i just wanna use navigationBar and i cant do this.

> Exception:  System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

i navigate to pages like this

>await _navigationService.NavigateAsync(nameof(CustomBarcodeScannerView), animated: true);

im using xamarin forms shared

**Comment by brianlagunas** [comment] 2017-08-27 18:33
Yo have to provide a sample application that can reproduce the issue.  There is not enough information in this issue to guess at what the issue is.

Also, don't use shared project, use a PCL.

**Comment by brianlagunas** [comment] 2017-08-29 13:53
I am closing since there has not been a response.

**Closed by brianlagunas** 2017-08-29 13:53 UTC
