### ISSUE TITLE
Sign assemblies with a strong name in NuGet packages

### ISSUE THREAD

**Issue by appel1** [PrismLibrary/Prism#224] opened 2015-10-14 14:29 UTC
We'd like to have strong names for our assemblies and it'd be nice if Prism did too.

**Comment by bartlannoeye** [comment] 2015-10-14 14:36
Duplicate of #70 

Hey @appel1 , we already implemented signing in PR #182 and will push new (signed) assemblies to NuGet with the next release (which will most likely be in the upcoming days).

**Closed by bartlannoeye** 2015-10-14 14:36 UTC

**Comment by appel1** [comment] 2015-10-14 15:03
Thanks. Thought I had included closed issues in my search but apparently not.
