### ISSUE TITLE
[BUG] Prism.Maui Modal Navigation with KnownNavigationParemeters.UseModalNavigation not working

### ISSUE THREAD

**Issue by tbaggett** [PrismLibrary/Prism#3046] opened 2024-01-10 20:50 UTC
### Description

NOTE: This issue may be related to https://github.com/PrismLibrary/Prism/issues/3031, where it is reported that the KnownNavigationParameters.Animated property is also ignored.

Normal navigation (as opposed to modal navigation) is seen on iOS when UseModalNavigation is set to true in Prism.Maui v9.0.349-pre. 

The app root page is a NavigationPage, which contains MainPage with buttons to navigate to ModalPage using either Prism INavigationService.NavigateAsync or MAUI Application.MainPage.Navigation.PushModalAsync methods.

The Prism navigation adds the ModalPage to the normal navigation stack. We see the navigation bar with a back arrow on the page after calling NavigationAsync with nav params indicating modal navigation should be used.

The MAUI navigation pops the ModalPage up on top of the MainPage as expected.

Repro project including more details and video of project in action available at https://github.com/tbaggett/PrismMauiModalNavTest

### Steps to Reproduce

1. Launch provided test app on the iOS simulator
2. Tap the "Navigate to Modal Page with Prism" button. ModalPage will be pushed onto the regular navigation stack from screen right to left
3. Tap the back arrow to return to MainPage
4. Tap the "Navigate to Modal Page with MAUI" button. ModalPage will appear on top of the MainPage as a modal, navigated from the bottom of the screen to the top

NOTE: I have only tested on iOS. This may/may not be an issue on Android or other platforms.

### Platform with bug

.NET MAUI

### Affected platforms

iOS

### Did you find any workaround?

No

**Comment by bkaankose** [comment] 2024-01-17 13:30
I think it's a duplicate of #2956

**Comment by dansiegel** [comment] 2024-01-20 20:09
Thanks @tbaggett I'm closing this as a duplicate but this should be fixed soon

**Closed by dansiegel** 2024-01-20 20:09 UTC
Labels: bug, duplicate, MAUI
