### ISSUE TITLE
Xamarin Forms UWP app with Prism Master Detail template - Memory usage is increasing for every menu click navigation and it is not reducing.

### ISSUE THREAD

**Issue by Mariselvam93** [PrismLibrary/Prism#2702] opened 2022-06-07 06:41 UTC
We have developed an UWP app using Xamarin Forms with Prism Master Detail template . We have couple of menus. 

### Steps to Reproduce

1. Login to UWP App and navigate to Dashboard page
2.  Navigate to another page from the left side menu
3. do it step 2 couple of times

### Expected Behavior
After navigating to another page, the current page instances removed from the navigation stack. 
### Actual Behavior
Navigation stack is not clearing page instances after navigating to another page.

### Basic Information

- Version with issue:
- Last known good version:
- Xamarin.Forms version: 5.0.0.1874
- IDE: Visual Studio 2022

### Screenshots
Referenced Packages
![image](https://user-images.githubusercontent.com/6279130/172308668-7a3a06d5-e4c1-44e0-80a0-f6ff5c068d35.png)

Dashboard Page
![image](https://user-images.githubusercontent.com/6279130/172312246-cc804944-8332-4651-bb1e-3e494a354022.png)

After navigating to some pages
![image](https://user-images.githubusercontent.com/6279130/172312733-9de8d351-a616-408c-87fd-a9f8bd80a5c6.png)

**Comment by brianlagunas** [comment] 2022-06-07 15:54
Closing because the required reproduction app was not provided. Also, no proof that objects are being rooted and not released. The task manager is not a reliable source to indicate a memory leak. Use a proper profiling tool and identify which objects are being rooted. Most memory leaks are due to developer code, not Prism.

**Closed by brianlagunas** 2022-06-07 15:54 UTC
Labels: bug, to verify
