### ISSUE TITLE
[Bug] Error CS0229 Ambiguity between 'Resource.Layout.Tabbar' and 'Resource.Layout.Tabbar' .Android\MainActivity.cs 15 Active

### ISSUE THREAD

**Issue by Kylar182** [PrismLibrary/Prism#2183] opened 2020-08-27 10:49 UTC
### Description
Error CS0229 Ambiguity between 'Resource.Layout.Tabbar' and 'Resource.Layout.Tabbar' .Android\MainActivity.cs 15 Active
Error CS0229 Ambiguity between 'Resource.Layout.Toolbar' and 'Resource.Layout.Toolbar' .Android\MainActivity.cs 16 Active

Sample
https://github.com/Kylar182/Prism4.8App 

### Steps to Reproduce

1. Update to Xamarin Forms 4.8
2. Get Errors

### Expected Behavior
not Getting errors

### Actual Behavior
Getting errors

### Basic Information

- Version with issue:
- Last known good version: 7.2.0.1422 (with 4.7 Xam Forms)
- Xamarin.Forms version: 7.2.0.1422
- IDE: Any

### Reproduction Link

https://github.com/Kylar182/Prism4.8App

**Comment by dansiegel** [comment] 2020-08-27 14:17
Duplicate of https://github.com/PrismLibrary/Prism.Templates/issues/20

This is a Design Time bug with the Android SDK and should not affect your builds. You can track the issue issue here: https://github.com/xamarin/xamarin-android/issues/4981

**Closed by dansiegel** 2020-08-27 14:17 UTC
Labels: bug, to verify
