### ISSUE TITLE
[UWP] Handle DevGestureService.GoBackRequested doesn't work

### ISSUE THREAD

**Issue by diego2k** [PrismLibrary/Prism#109] opened 2015-08-27 09:14 UTC
Hi,
since the last updates I can't handle the hardware go back button on my own. 

    DevGestureService.GoBackRequested += GoBackRequested;

    private void GoBackRequested(object sender, Prism.Windows.AppModel.DeviceGestureEventArgs e)
     {
            if (...)
            {
                ...
            }
            else
            {
                NavService.GoBack();
            }
            e.Cancel = true;
            e.Handled = true;
      }

It's not important which branch is called the result is every time a go back. 

In the commit b5468fd0fd58e3f48872379d23a409ea538786bd from https://github.com/jorisdebock/Prism.git everything worked fine, but in the current head commit 130bf2a715730f474d36f3e91e1b0f39d4eeb698 from https://github.com/PrismLibrary/Prism.git the issue occurs.  
Thanks!

**Comment by veccie** [comment] 2015-08-27 12:46
I can't really find any differences between the two commits when looking at PrismApplication, but while testing a few things I found out why it isn't working in certain scenarios.

Initially I made it so that back events get fired in reverse, but if you hook on to GoBackRequested from CreateDeviceGestureService() then the default behavior will get fired first.

This can be avoided if you for example hook on to GoBackRequested from say OnInitializeAsync() by accessing the Property: DeviceGestureService.GoBackRequested += ...

Then it works :)

There's also still some old code that needs to be removed which I've done here #105 and maybe the e.handled and e.cancel should be handled too in case you hook onto to events from CreateDeviceGestureService()

I can make a PR for that too :)

What do you think @briannoyes ?

**Comment by diego2k** [comment] 2015-08-27 20:13
Thanks, 
I'm definitely hooking it after CreateDeviceGestureService() is called, actually it's in the Loaded method of an page. I have looked a little bit into the Prism code: 
First PrismApplication.HardwareButtonsOnBackPressed gets called and thus the _frame.GoBack();
Then RaiseCancelableEvent<T>(EventHandler<T> eventHandler, object sender, T args) which calls my method; "if (args.Cancel)" gets true and thus the loop ends. 
But it's not important at this point in time _frame.GoBack(); is already called ... 

Currently I don't get how this should work, PrismApplication.InitializeFrameAsync subscribes directly to HardwareButtons.BackPressed, so there is no potability to cancel the event.

**Comment by veccie** [comment] 2015-08-27 22:57
I'm still not sure why it's acting differently in your case. I'm not able to reproduce this myself.

Can you reproduce the same problem using the HelloWorld sample?

**Comment by diego2k** [comment] 2015-08-28 12:36
Sure :)
Take the HelloWorld from the master, change the UserInputPage.xaml.cs to:

    public sealed partial class UserInputPage : VisualStateAwarePage
    {
        public UserInputPage()
        {
            InitializeComponent();
            this.Loaded += (s, e) => { App.DEV.GoBackRequested += GoBackRequested; };
        }

        private void GoBackRequested(object sender, Prism.Windows.AppModel.DeviceGestureEventArgs e)
        {
            // NOP
            e.Handled = true;
            e.Cancel = true;
        }
    }

And of course you have to edit  the App.xaml.cs, add this line:

        public static IDeviceGestureService DEV { get; set; }

and but this line in the OnLaunchApplicationAsync method:

            DEV = this.DeviceGestureService;

Start the app with the "Mobile Emulator 10.0.10240.0 WVGA 4 inch 512MB", select an item and click "Navigate To", now press the hardware back button (bottom left). 
You will see that the app navigates one page back. 
So what happened? 
The RaiseCancelableEvent will be called, but my GoBackRequested method from the top will just to a NOP, so no navigation will happen. But in the PrismApplication.cs the method HardwareButtonsOnBackPressed gets also called which triggers the GoBack event. 

If you start the app without my modification, the back button will close the app, this is comprehensible because the GoBack event will be called twice, one time by this line: 

    HardwareButtons.BackPressed += HardwareButtonsOnBackPressed;

and one time by this: 

    DeviceGestureService.GoBackRequested += OnGoBackRequested;

I have compared the two mentioned versions and this is exactly what got changed, just remove this lines from PrismApplication.InitializeFrameAsync and the bug should be fixed: 

    if (ApiInformation.IsEventPresent("Windows.Phone.UI.Input.HardwareButtons", "BackPressed"))
    {
        HardwareButtons.BackPressed += HardwareButtonsOnBackPressed;
     }

You have already subscribed the HardwareButtons.BackPressed in the DeviceGestureService.InitializeEventHandlers. I think I don't have to explain way this problem ;).

Thanks,
Harald

**Comment by veccie** [comment] 2015-08-28 13:28
As I mentioned in my first comment I have already submitted a PR #105 to fix/remove the old code.

I believe its leftover code from @briannoyes' manual merge, because it's not there in my original PR.

When/if my PR #105 gets merged the problem should be solved :)

**Comment by diego2k** [comment] 2015-08-28 14:09
Ah I'm sorry I didn't read #105 
Perfect thanks!

**Comment by briannoyes** [comment] 2015-08-28 16:49
I'll try to get it in this evening, if not first priority tomorrow.

**Comment by veccie** [comment] 2015-08-29 21:38
Can you confirm that it works again @diego2k now that #105 has been merged?

**Comment by diego2k** [comment] 2015-08-30 17:29
Looks pretty good,
thanks

**Closed** 2015-09-03 19:01 UTC
