### ISSUE TITLE
Cannot create prism project by Xamarin Studio on Mac

### ISSUE THREAD

**Issue by vulcanlee** [PrismLibrary/Prism#816] opened 2016-10-23 10:39 UTC
Today, I have update my Xamarin studio to lastest version and install Prism Template Pack 1.4 of Add-ins into Xamarin Studio.

But If I click [File] > [New Solution] > [Prism Unity App] and create iOS and Android solution, on Package Console will stay on "Attempting to gather dependency information for package 'Prism.Unity.Forms.6.2.0-pre5' with respect to project 'a2.iOS', targeting 'Xamarin.iOS,Version=v1.0'" and this solution cannot to be created.

You can reference my operation video recod :  https://youtu.be/2OTkFsJvqRc

https://youtu.be/2OTkFsJvqRc

### Package info

- Xamarin Studio version : 6.1.1(Build 15)
- Prism Add-ins version 1.4
- Platform: Mac

**Comment by brianlagunas** [comment] 2016-10-24 14:58
Duplicate of #814 .

**Closed by brianlagunas** 2016-10-24 14:58 UTC

**Comment by brianlagunas** [comment] 2016-11-02 00:10
Can you install 1.5 and see if it works for you?
