### ISSUE TITLE
Update Reference to CommonServiceLocator

### ISSUE THREAD

**Issue by Dirkster99** [PrismLibrary/Prism#1283] opened 2017-11-25 19:07 UTC
Is it possible to upate the reference to the CommonServiceLocator (version 2.1)?

I cannot seem to get the Prism project compiled so I cannot create a PR, but updating this should not be more work then search replace name spaces:

      Find: using Microsoft.Practices.ServiceLocation
Replace: using CommonServiceLocator

It would be great if we could get this update because other projects depending on Prism are restricted to version 1.3 - which has cost me quit some time to figure out ....

**Comment by bartlannoeye** [comment] 2017-11-25 20:58
Duplicate of #1211, already solved by #1240. If you use the pre-release version currently on NuGet, you will be able to use CommonServiceLocator v2. More info of the release can be found in the [release notes](https://github.com/PrismLibrary/Prism/releases/tag/7.0.0-pre4).

**Closed by bartlannoeye** 2017-11-25 20:58 UTC
