### ISSUE TITLE
[UWP] Prism.Windows.PrismApplication constructor throws an ArgumentNullException when compling with .Net Native Toolchain

### ISSUE THREAD

**Issue by Haplois** [PrismLibrary/Prism#386] opened 2016-01-09 23:16 UTC
CreateLogger method returns a DebugLogger object by default, and this object's Log method is failing.

	[System.ArgumentNullException] {System.ArgumentNullException: ArgumentNull_Generic}
		at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args) in f:\...\src\System.Private.CoreLib\System\String.cs:line 2857
		at System.String.Format(IFormatProvider provider, String format, Object[] args) in f:\...\src\System.Private.CoreLib\System\String.cs:line 2836
		at Prism.Logging.DebugLogger.Log(String message, Category category, Priority priority)
		at Prism.Windows.PrismApplication..ctor()
		at Tcm.Sfa.Windows.App..ctor() in D:\...\App.xaml.cs:line 48
		at Tcm.Sfa.Program.Run(ApplicationInitializationCallbackParams p) in D:\...\Program.cs:line 15
		at System.Func`2.InvokeOpenStaticThunk(T arg)
		at Windows.UI.Xaml.ApplicationInitializationCallback__Impl.Vtbl.Invoke__STUB(IntPtr pComThis, Vtbl** unsafe_p) in d:\...\obj\x64\Release\ilc\intermediate\Tcm.Sfa.Windows.Interop\ImplTypes.g.cs:line 166157}	System.ArgumentNullException

Repro: https://github.com/Haplois/prism-argnull-repro

**Comment by MattWhilden** [comment] 2016-01-11 22:52
I work on the .NET Native compiler team. Tag me if you think this is something that warrants investigation from our side.

**Comment by brianlagunas** [comment] 2016-01-11 23:00
I'm glad you said something @MattWhilden.  We have actually run into a number of problems related to the .NET Native compilation.  This is the most recent report, but we also has reports related to serialization in issue #333, though I think we may have a work around for that.  Not sure, I will have to double check the issue.  We still have to verify this particular issue specifically, but it does work in debug mode :)

**Comment by MattWhilden** [comment] 2016-01-11 23:05
Thanks Brian. Happy to help out. Our normal workflow for these kinds of things is outlined here: https://github.com/dotnet/core/blob/master/Documentation/ilcRepro.md.

**Comment by Haplois** [comment] 2016-01-11 23:07
I does work on Debug mode, and Release mode when Native toolchain is disabled.

**Comment by brianlagunas** [comment] 2016-01-11 23:08
Thanks @MattWhilden, that's great to know!

**Comment by MattWhilden** [comment] 2016-02-16 07:25
We have a preview build of the Update 2 version of the .NET Native toolchain that we'd be happy to share with y'all if you think there's value. It may correct some issues you're seeing or help us identify other issues before we ship. Just shoot me a mail at dotnetnative@microsoft.com to get hooked up.

**Comment by csongysun** [comment] 2016-02-22 18:45
It seems that
[DebugLogger.cs](https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Logging/DebugLogger.cs#L21
)
`Resources.DefaultDebugLoggerPattern` is null.
i found that the resourceManager return null at
[Resources.Designer.cs](https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Properties/Resources.Designer.cs#L87)
set resourceCulture "en-US" then code goes well.
`        private static global::System.Globalization.CultureInfo resourceCulture = new System.Globalization.CultureInfo("en-US");
`

**Comment by brianlagunas** [comment] 2016-02-22 19:18
Interesting, what's your default culture?

**Comment by csongysun** [comment] 2016-02-22 20:03
zh-CN

**Comment by brianlagunas** [comment] 2016-02-22 20:05
@MattWhilden have you had similar issues reported when using resource files and compiling with the .NET Native toolchain?

**Comment by MattWhilden** [comment] 2016-02-22 20:07
Very interesting. I haven't seen anything like this. Can someone describe how to get this set up locally? A link to a clonable repo is perfect but I'm happy to follow a list of steps (ex: get XXX nuget package, type this code etc).

**Comment by Haplois** [comment] 2016-02-22 20:13
@MattWhilden  Repro I posted exactly demonstrates this issue. If a resource file now found for a current culture it throws on native, assumes English on debug.

**Comment by MattWhilden** [comment] 2016-02-22 20:17
Thanks for pointing that out! Been juggling lots of other things and I confused this with another thing I'm tracking down. My apologies. I'll try to take a look today or tomorrow.

**Comment by Haplois** [comment] 2016-02-22 20:21
Glad if I helped.

**Comment by MattWhilden** [comment] 2016-02-26 18:04
Figured I'd leave a note here that we're convinced this is a bug in the .NET Native compiler and how it handles resources. Will keep you all posted.

**Comment by brianlagunas** [comment] 2016-02-26 18:09
Thanks for the update.  I'll leave this issue open until a fix has been confirmed in the .NET Native compiler so that all interested parties will be notified when the fix is available.

Thanks again!

**Comment by MattWhilden** [comment] 2016-02-29 23:18
This is an issue inside of our ResourceManager. Here's the PR over on our GitHub to get this corrected: https://github.com/dotnet/corefx/pull/6525/commits. Presumably you'll be able to get this fix from our feeds in a few days but I haven't tried it personally yet.

Is this currently blocking anyone? Do they have "suitable" workarounds? It helps to know these things so that we can correctly assess how quickly to get these fixes into the official feeds etc.

Really appreciate the bug report sorry it took so long to get chased down.

**Comment by Shinoa-best-girl** [comment] 2016-03-01 15:39
> Presumably you'll be able to get this fix from our feeds in a few days
Could you please explain me how to consume prerelease bits and bytes.
I tried to update Microsoft.NETCore.UniversalWindowsPlatform package from these feeds:
https://www.myget.org/F/aspnetmaster/api/v2/
https://www.myget.org/F/aspnetvnext/api/v2/

I get these errors while using aspnetvnext:
Restoring packages for 'App8'.
Restoring packages for D:\Visual Studio 2015\Projects\App8\App8\project.json...
All packages are compatible with UAP,Version=v10.0.
System.AppContext 4.1.0-rc2-23819 provides a compile-time reference assembly for System.AppContext on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm.
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
System.AppContext 4.1.0-rc2-23819 provides a compile-time reference assembly for System.AppContext on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
System.AppContext 4.1.0-rc2-23819 provides a compile-time reference assembly for System.AppContext on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86.
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
System.AppContext 4.1.0-rc2-23819 provides a compile-time reference assembly for System.AppContext on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
System.AppContext 4.1.0-rc2-23819 provides a compile-time reference assembly for System.AppContext on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64.
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
System.AppContext 4.1.0-rc2-23819 provides a compile-time reference assembly for System.AppContext on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
Package restore failed for 'App8'.
Package restore failed. Rolling back package changes for 'App8'.
========== Finished ==========

aspnetmaster feed works ok for me, but it contains beta packages released in 2015 year.

**Comment by MattWhilden** [comment] 2016-03-01 18:53
Sadly, it's a bit more complicated than just pulling down that one package. This is because many of those packages have tight couplings to implementation dlls that ship separately with the .NET Native compiler and runtime. I'll work on getting some instructions together so that you we can properly test this.

I have a couple other issues that will keep me busy today so I may not get to it immediately.

**Closed** 2016-03-02 22:49 UTC
Labels: UWP

**Comment by michelebonomelli** [comment] 2016-05-31 09:14
Hi,
I have the same problem with my UWP app.
There is a fix or a workaround?
