### ISSUE TITLE
Prism 8 Tabbed pages don't set the BindingContext correctly 

### ISSUE THREAD

**Issue by liveinvarun** [PrismLibrary/Prism#2317] opened 2021-01-24 16:14 UTC
### Description

I have used the sample app in Prism and when we have set the Mainpage like in the sample.

 <NavigationPage Title="Page A" >
        <x:Arguments>
            <views:APage Title="Page A"/>
        </x:Arguments>
        <NavigationPage.Behaviors>
            <prim:NavigationPageActiveAwareBehavior/>
        </NavigationPage.Behaviors>
    </NavigationPage>
    ......
    </NavigationPage>

 Since we had defined the Register for Navigation Atrributes also why does the view BindingContext is set to MainPageViewModel?
when i debug i see Apage  BindingContext is set as MainViewModel. Ideally it should be set as ApageViewModel.
This works fine with other version of Prism 7.2. 
Register for 

### Expected Behavior
Binding Cntxt for ApageView inside Tab should be APageViewModel 
### Actual Behavior

Binding Cntxt for ApageView  is parent MainPageVM
### Basic Information

- Version with issue: Prism8 ,
- Last known good version:7.2
- Xamarin.Forms version:Forms 4.8
- IDE:VS for MAC

### Reproduction Link
https://github.com/PrismLibrary/Prism/files/5422413/SampleApp.zip

**Comment by dansiegel** [comment] 2021-01-28 16:06
closing as duplicate of #2218

**Closed by dansiegel** 2021-01-28 16:06 UTC
Labels: bug, duplicate, to verify
