### ISSUE TITLE
Support for Xamarin Form Shell? 

### ISSUE THREAD

**Issue by huyjack178** [PrismLibrary/Prism#1809] opened 2019-05-27 08:28 UTC
### Description

Add support for Xamarin Forms Shell

**Comment by dansiegel** [comment] 2019-05-27 15:40
Technically speaking if all you want is the VML with DI, you can use Prism today with Shell and away you go. Before Prism can properly support Shell we need the Forms team to make some changes as you can see [here](/xamarin/xamarin.forms/issues/5166). Once we're able to properly support Shell we will look at introducing official support for it.

**Comment by huyjack178** [comment] 2019-05-28 02:57
@dansiegel Hope to see it soon :D

**Comment by dansiegel** [comment] 2019-05-29 02:28
@huyjack178 don't hold your breath... we've been waiting since October...

**Comment by marxxxx** [comment] 2019-07-01 18:13
@dansiegel If we want to use the full Prism functionality including Navigation, would you suggest to stick with XF 3 and Prism and wait with the upgrade to XF 4 until full support has been established or is it safe to start with XF 4 without using Shell?

**Comment by brianlagunas** [comment] 2019-07-01 18:16
Prism is always safe to use without Shell :)

**Comment by ninaada** [comment] 2019-07-04 15:11
@marxxxx We are already using XF 4.0 with Prism 7.1. No problems whatsoever. Its working like it has been.

**Comment by Im-PJ** [comment] 2019-07-05 11:43
There is progress from Forms team https://github.com/xamarin/Xamarin.Forms/pull/6764
Lets wait for Prism team now..

**Comment by dansiegel** [comment] 2019-07-05 12:35
@Im-PJ I’m in regular contact with the Forms team on this and several other issues. This functionality isn’t planned for any integration until Prism 7.3.

**Comment by Sonnenspeer** [comment] 2019-07-05 19:51
Is there a roadmap for Prism? Would like to know when 7.3 could be expected.

**Comment by developer9969** [comment] 2019-11-10 07:39
Hi there,
would it be possible to have an update on support on shell? I know you depend on XF but is there any movements? Whether shell is a good or bad thing they are really adding lots of features to it and we would like to continue to use prism and it's goodness but integrate with shell?

Many thanks

**Comment by dansiegel** [comment] 2019-11-20 15:52
I had a call with @pureween on Shell yesterday. Currently working on a POC, but we'll need some additional changes from the Spike build that we can test with.

**Comment by dansiegel** [comment] 2020-01-06 18:31
for anyone interested in this issue I will be streaming on Twitch with @PureWeen on Thursday afternoon to look more into this.

**Comment by brianlagunas** [comment] 2020-01-06 18:39
@dansiegel Time (with timezone), and link to your Twitch please 😄

**Comment by dansiegel** [comment] 2020-01-06 18:48
will be posting that as soon as it's confirmed

**Comment by dansiegel** [comment] 2020-01-07 17:40
Ok confirming we will be streaming 2pm PST January 9th 

https://www.twitch.tv/xamarinformsteam/

**Comment by KevinHu-au** [comment] 2020-01-09 22:26
@dansiegel, the link you posted is bringing me to an offline video "Shell - Hacking away at the Flyout".  Shane mentioned in the video that he would have a video with you to talk about the integration between Shell and Prism. Can you show us the link for the video? Thanks

**Comment by dansiegel** [comment] 2020-01-09 22:47
@KevinHu-au Shane got delayed with a meeting... we should be starting soon

**Comment by hudaIT** [comment] 2020-02-11 13:28
Any updates on this?

**Comment by erodezhao** [comment] 2020-02-26 05:49
Support shell?

**Comment by dansiegel** [comment] 2020-02-26 15:09
you can see any changes we do in this [repo](https://github.com/dansiegel/Prism-Shell-Stream).

**Comment by jmeyerworms** [comment] 2020-03-19 20:47
any news ? shell is now supported ?

**Comment by brianlagunas** [comment] 2020-03-19 20:51
Everyone will know when Shell is supported when this issue is "Closed".

Is this issue still open?
* Yes, it's still open - Shell is NOT supported
* No, it's closed - Shell support has been added

Locking conversation

**Comment by dansiegel** [comment] 2020-04-22 21:00
Note this issue is on hold likely until after Microsoft Build. If someone would like to work on this issue you can find the appropriate working project [here](https://github.com/dansiegel/Prism-Shell-Stream). Keep in mind that this sample repo uses both Prism and Xamarin.Forms as Git Sub Modules and builds both from source... this is not for the faint of heart...

**Comment by dansiegel** [comment] 2020-08-11 17:51
Unfortunately it does not look like the branch that Shane and I were working on will be merged in the Xamarin.Forms. We do currently have an experimental branch that would require less drastic changes to work with Shell, but likely would not be supported until Xamarin.Forms 5.0 releases. 

It's also likely that any release that we may do will be considered "Experimental" and may not work quite the same as you are used to with traditional Prism Navigation.

You can continue to find the working sample repo [here](/dansiegel/Prism-Shell-Stream). 

For those of you who are "dying to use Shell", please feel free to clone that repo and play around with it, update the sample app to have a layout like you want in one of your apps and let us know there if there are changes you want or features you "NEED" that aren't currently supported.

**Comment by brianlagunas** [comment] 2021-03-24 20:30
After careful consideration, the Prism team has decided not to implement support for Shell.

**Closed by brianlagunas** 2021-03-24 20:30 UTC
Labels: XF, blocked by platform, enhancement
