### ISSUE TITLE
[Bug] AutoInitialize attribute doesn't override automatic name matching

### ISSUE THREAD

**Issue by Inrego** [PrismLibrary/Prism#2154] opened 2020-07-27 10:36 UTC
### Description
When navigating with parameters, the autoinitialization tries to set matching property name even though there's an attribute to redirect the parameter to another property. Maybe it's working as expected, but then I'd advise to elaborate a bit on the documentation page.

Example:

    public class TestPageViewModel : BindableBase, IAutoInitialize
    {
        private string _previousValue;
        [AutoInitialize("Value")]
        public string PreviousValue
        {
            get => _previousValue;
            set => SetProperty(ref _previousValue, value);
        }

        private string _value;
        public string Value
        {
            get => _value;
            set => SetProperty(ref _value, value);
        }
    }

And navigating like this, will cause both `PreviousValue` and `Value` to be set to `"value from previous page"`:

    await NavigationService.NavigateAsync(nameof(TestPage), new NavigationParameters
    {
        {"Value", "value from previous page"}
    });

### Expected Behavior
Just `PreviousValue` will be auto initialized.

### Actual Behavior
Both `PreviousValue` and `Value` are auto initialized. Also, if they're not the same type, navigation fails with a casting exception.

### Basic Information

- Version with issue: 7.2.0.1422
- Last known good version: ??
- Xamarin.Forms version: 4.6.0.800
- IDE: Visual Studio 16.6.3

### Reproduction Link
Small reproduction sample is provided as code snippets in the issue description.

**Comment by brianlagunas** [comment] 2020-07-30 17:31
This is behaving as expected. If you have a property names the same as an incoming parameter, and also force that same parameter to be assigned to another differently named property, we must set both. This feature is working by design.

**Closed by brianlagunas** 2020-07-30 17:31 UTC

**Comment by stanleywailers** [comment] 2021-01-27 22:27
yeah I had the same question @Inrego 

can you bring us an example to use this feature correctly @brianlagunas ? have a nice day
