### ISSUE TITLE
[Bug]  DryIoc update to 5.0.0, Invoke new DryIocContainerExtension(new Container(DefaultRules) throw exception.

### ISSUE THREAD

**Issue by NickNameIsNull** [PrismLibrary/Prism#2679] opened 2022-04-16 16:27 UTC
### Steps to Reproduce

1. nuget update DryIoc to 5.0.0；
2. Invoke DryIocContainerExtension(new Container(DefaultRules)；
3. Run Project；

### Expected Behavior
No exception

### Actual Behavior
throw exception.

### Basic Information

- Version with issue: 
DryIoc:5.0.0

- Last known good version:
DryIoc:4.8.8

- Prism.DryIoc version:8.1.97

- IDE:VS 2020

### Screenshots

![image](https://user-images.githubusercontent.com/16376037/163683110-8ef99fbc-6992-4c07-bcd9-ac558d5b410b.png)

![image](https://user-images.githubusercontent.com/16376037/163683191-3352a545-efc6-4584-9607-b90ac99fe9af.png)

### Reproduction Link

![image](https://user-images.githubusercontent.com/16376037/163683208-90fc89b3-086b-4f7c-9508-c00cfa319909.png)
https://github.com/dadhi/DryIoc/blob/43638a71315d6be326df7e211649d436594aff48/docs/DryIoc.Docs/ResolutionPipeline.md#ruleswithoutfastexpressioncompiler

![image](https://user-images.githubusercontent.com/16376037/163683256-30a43744-757a-48b4-9f2b-99e06fe3f4b0.png)

https://github.com/PrismLibrary/Prism/blob/342689ba9a10e511418943438d0f5c57534ca623/src/Containers/Prism.DryIoc.Shared/DryIocContainerExtension.cs

**Comment by NickNameIsNull** [comment] 2022-04-16 16:33
DryIoc VersionHistory:
https://github.com/dadhi/DryIoc/blob/b7b5c0231853cdfcbd034d165fd376e92c1f82d2/docs/DryIoc.Docs/VersionHistory.md
![image](https://user-images.githubusercontent.com/16376037/163683477-ceb5cd0b-9f88-46fa-8ebc-f1e57509fab2.png)

**Comment by brianlagunas** [comment] 2022-04-16 21:50
This is a duplicate of #2677. As stated in that issue, you can't update the DryIoC version that Prism depends on and expect it to work. Prism relies on DryIoC v4.7.7. If you upgrade DryIoC separately, you take the risk of incompatibility issues.

When an update of Prism is released, the dependencies will also be upgraded.

**Closed by brianlagunas** 2022-04-16 21:50 UTC
Labels: bug, to verify

**Comment by mzy666888** [comment] 2022-05-06 08:02
When will the next version be released？
