### ISSUE TITLE
[Bug] An unexpected error occurred while resolving 'Prism.Regions.IActiveRegionHelper'

### ISSUE THREAD

**Issue by Nobody84** [PrismLibrary/Prism#2233] opened 2020-11-02 16:04 UTC
### Description
I have build a simple Xamarin.Forms app using the latest `Prism.Unity.Forms` and `Prism.Forms.Regions`to test the new Region feature. Calling `regionManager.RequestNavigate` gives me an unsuccessfull navigation result with the error message: 
`An unexpected error occurred while resolving 'Prism.Regions.IActiveRegionHelper'`

Maybe it's related to [https://github.com/PrismLibrary/Prism/issues/2227](https://github.com/PrismLibrary/Prism/issues/2227), but I didn't get any exception. Even if I run the application provided by in [https://github.com/PrismLibrary/Prism/issues/2227](https://github.com/PrismLibrary/Prism/issues/2227) I didn't get the mentioned exception, instead I also get a `RegionNavigationResult` with the error message shown above. 

### Steps to Reproduce

1. Debug the App on Android or UWP
2. Click on the `View A` button.
3. The `RegionNavigationResult` result and error message will be displayed.

### Expected Behavior
`View A` should be displayed in the region named `MainRegion`.

### Actual Behavior
The `RegionNavigationResult.Result` is `false` and the error message is `An unexpected error occurred while resolving 'Prism.Regions.IActiveRegionHelper'`.

### Basic Information

- Version with issue: Prism.Forms.Regions 8.0.0.1909
- Last known good version: none
- Xamarin.Forms version: 4.8.0.1560
- IDE: Visual Studio Community 16.7.7

### Screenshots
![grafik](https://user-images.githubusercontent.com/8879706/97889032-24513380-1d2c-11eb-9b07-60e3c5c56095.png)

### Reproduction Link
https://github.com/Nobody84/Prototype.XF.Prism.RegionNavigation

**Comment by AngelSanchez87** [comment] 2020-11-24 10:13
Is there any solution for this? Thanks!

**Comment by dansiegel** [comment] 2020-11-24 16:17
Closing as this is a duplicate of #2227

**Closed by dansiegel** 2020-11-24 16:17 UTC
Labels: XF, bug, duplicate
