### ISSUE TITLE
Navigating to Detail Page fires OnNavigatedTo twice on IOS

### ISSUE THREAD

**Issue by xalikoutis** [PrismLibrary/Prism#1460] opened 2018-06-01 13:58 UTC
### Description

Navigating to DetailPage through MasterPage in IOS fires twice OnNavigatedTo. This works just fine in Android

### Steps to Reproduce

Suppose you have 3 detail pages A,B,C when navigating 
from A->B or B->A or B->C fires twice
from A-> A or B->B fires once

This how i navigate from MasterDetailPage
`NavigationService.NavigateAsync("NavigationPage/DeviationsPage"); `

### Expected Behavior
OnNavigatedTo should be called once
### Actual Behavior
OnNavigatedTo is called twice
### Basic Information

- Version with issue: Prism 7.0.0.396
- Xamarin.Forms version:3.0.0.482510
- IDE: Visual Studio

Only on IOS

Reproduction link
https://www.dropbox.com/s/2hknjpgelmbg4b2/TwiceNav.rar?dl=0

**Comment by brianlagunas** [comment] 2018-06-01 14:00
Closing as you did not provide the required reproduction link.  Also , there is no navigation code specific to iOS or Android. All navigation uses the built-in XF navigation API.

**Comment by xalikoutis** [comment] 2018-06-01 15:09
Added a reproduction link

**Comment by brianlagunas** [comment] 2018-06-01 15:39
Thanks for the link, we'll look into it.

**Comment by dansiegel** [comment] 2018-06-01 20:39
This is absolutely a huge bug in 7.0. for some reason OnNavigatedTo is being called after OnNavigatingTo and both before and after OnNavigatedFrom on iOS... while the second part with OnNavigatedFrom/To doesn't get called on Android. Good news is that it is already fixed, and works as expected in 7.1.

**Closed by dansiegel** 2018-06-01 20:39 UTC
Labels: XF, bug

**Comment by brianlagunas** [comment] 2018-06-01 20:42
Just to be clear, this was not a bug in Prism :).  Xamarin must have broken something and then fixed it in the latest release.  We haven't touched that logic for INavAware in a very long time.

**Comment by xalikoutis** [comment] 2018-06-02 00:20
I am little bit confused, whats the solution? If it is a XF problem should i update in a pre-release

**Comment by brianlagunas** [comment] 2018-06-04 14:49
You could try upgrading your version of XF to the latest, or just start using the current preview of Prism 7.1
