### ISSUE TITLE
GoBackTo with parameters

### ISSUE THREAD

**Issue by berhir** [PrismLibrary/Prism#2817] opened 2023-01-20 09:27 UTC
When I navigate to a page, I use the navigation builder this way:

```cs
await NavigationService.CreateBuilder()
            .AddSegment<DetailsViewModel>()
            .AddParameter("Id", id)
            .NavigateAsync();
```

Now I tried to do the same with GoBackTo:
```cs
await NavigationService.CreateBuilder()
            .AddParameter("ReturnValue", val)
            .GoBackTo<OverviewViewModel>();
```

But it turned out that this doesn't work because the parameters are ignored. The parameters must be set directly in the call to `GoBackTo<OverviewViewModel>(myParams)`.

I took a look at the `NavigationBuilder` code and found out that `NavigateAsync` takes the parameters from the `_navigationParameters` member variable while `GoBackTo` takes the method parameters directly.
```cs
public Task<INavigationResult> NavigateAsync()
{
    return _navigationService.NavigateAsync(BuildUri(), _navigationParameters);
}

public async Task<INavigationResult> GoBackTo<TViewModel>(INavigationParameters parameters)
{
    var name = NavigationBuilderExtensions.GetNavigationKey<TViewModel>(this);
    return await _navigationService.GoBackToAsync(name, parameters);
}
```

It would be great to change the behavior of `GoBackTo()` to be consistent with `NavigateAsync()`.
The most consistent way would be to remove the `parameters` parameter completely from the `GoBackTo()` method and require the usage of `AddParameter` or `WithParameters` (like it works for `NavigateAsync()`).

Also, the `GoBackTo` misses the `Async` suffix.

**Comment by dansiegel** [comment] 2023-02-21 18:02
Closing this as it is a duplicate of #2818 which you also opened and where more conversation on this topic has occurred.

**Closed by dansiegel** 2023-02-21 18:02 UTC
Labels: duplicate
