### ISSUE TITLE
[XF] NavigationService with MasterDetail on iOS.

### ISSUE THREAD

**Issue by rotsen24154** [PrismLibrary/Prism#1402] opened 2018-03-15 19:37 UTC
### Description
I have this strange behaivor using NavigationService with my MasterDetail on **iOS**.
When I click the option in the menu calls a command from the ViewModel

```
private async void OnNavigateCommandExecuted(string path)
{
    //await NavigationService.NavigateAsync(path);
    await NavigationService.NavigateAsync("Navigation/ReadCodeInstructionPage"); //For example
}
```
There is a slight delay when the transition is made between the pages, and back button appears and then disappears.
**On Android works perfectly.**

Am I doing something wrong or is a bug?

### Example
![](https://media.giphy.com/media/bL97XCY4vdBgEHxowC/giphy.gif)
>

**Comment by ali-h2010** [comment] 2018-04-16 17:54
I am facing similar interaction. I assumed it's natural behavior of iOS where the page that you will navigate to must be loaded before closing the drawer. 

That is why i added a small loading popup since if the page is heavy, it will be very slow to navigate to. 

the back button that appears is also typical behavior as i assumed that i am calling the 'NavigateAsync' which navigate to the page but it knows that it was called from a MD page, so it will convert the back button to the menu button

**Comment by brianlagunas** [comment] 2018-04-16 18:05
Sorry for the late response, I have been slammed at work.

Actually, this is somewhat by design.  First the detail page is navigated to and then the IsPresented property is set to false.  We could change this order, but then the navigation drawer would be closed and then the page would be navigated to which may be even more awkward.

As far as the back button showing and then hiding, this is the result of reusing the NavigationPage.  What happens is that the target page is navigated onto the NavigatoinPage's nav stack.  This causes the back arrow to show. Then the other page you are navigating away from is removed from the Navigationpage's stack and then the back button would disappear and then you get the hambuger menu.

This is a little trickier because we don't want to recreate the NavigationPage each time you navigate to it, but I can see where this back button flash can be a little annoying.

Not really sure what to do here

**Comment by ali-h2010** [comment] 2018-04-22 10:24
@rotsen24154 try the app with an iPad simulator. 
It uses different interaction.
If it's too slow even in iPad, you will need to use async and optimize your output to appear in a better way.

**Comment by brianlagunas** [comment] 2018-04-28 01:09
Did anyone have more thoughts on this? If not, I am going to close this issue.

**Comment by rotsen24154** [comment] 2018-04-29 00:50
Thanks, you can close it 👍

**Closed** 2018-04-29 01:02 UTC
Labels: XF
