### ISSUE TITLE
Request: Update Prism Template Pack to use latest release version of XF

### ISSUE THREAD

**Issue by adrianknight89** [PrismLibrary/Prism#1447] opened 2018-05-18 02:34 UTC
Template pack 2.0.9 is using XF 2.5. Can it be updated to use XF 3.0?

**Comment by dansiegel** [comment] 2018-05-18 02:36
any project created with the Template Pack shouldn't have an issue updating to 3.0... not sure exactly when but I'm sure we'll have an updated Template Pack out in the near future.

**Comment by adrianknight89** [comment] 2018-05-19 17:00
Thanks. Looking forward to an update.

**Comment by scxp** [comment] 2018-05-19 19:00
I'd like to see an updated template pack as well. Also, comparing Mobile App template to Prism Blank App template, I see some differences that can be removed. 

For example, the prism template is adding iTunesArtwork files while I don't see them in XF template.

`iTunesArtwork@1x.png`
`iTunesArtwork@2x.png`
`iTunesArtwork@3x.png`


Prism has the following in Info.plist whereas XF template does not.
```
<key>CFBundleIconFiles</key>
    <array>
      <string>Icon-60@2x</string>
      <string>Icon-60@3x</string>
      <string>Icon-76</string>
      <string>Icon-76@2x</string>
      <string>Default</string>
      <string>Default@2x</string>
      <string>Default-568h@2x</string>
      <string>Default-Portrait</string>
      <string>Default-Portrait@2x</string>
      <string>Icon-Small-40</string>
      <string>Icon-Small-40@2x</string>
      <string>Icon-Small-40@3x</string>
      <string>Icon-Small</string>
      <string>Icon-Small@2x</string>
      <string>Icon-Small@3x</string>
    </array>
```

XF Info.plist has the following whereas Prism does not:

```
        <key>CFBundleName</key>
	<string>App1</string>
	<key>XSAppIconAssets</key>
	<string>Assets.xcassets/AppIcon.appiconset</string>
```

In MainActivity.cs, RegisterTypes has the following comment, but this comment is missing in AppDelegate.cs (maybe remove it everywhere or add it to the second file for consistency?):
`// Register any platform specific implementations`

In both files, RegisterTypes is expecting a parameter named `container` even though `IPlatformInitializer` is expecting `containerRegistry`. (Observe that App.xaml.cs is also using `containerRegistry`)

iOS Resources folder has several Default pngs but XF template has only the LaunchScreen storyboard.

Prism is setting Android icon to `@mipmap/ic_launcher`, but XF sets it to `@mipmap/icon`

Prism is missing mipmap-anydpi-v26 folder with the two xml files.

Prism is missing drawable folders. Not an expert on this, but I think mipmap folders are used only for icons whereas all other images still go to drawable folders.

Prism is missing colors.xml

Prism is using ic_launcher images as opposed to Icon and is missing launcher_foreground.png in all mipmap folders.

Prism has Assets.xcassets folder, but XF no longer has it for iOS.

**Comment by scxp** [comment] 2018-05-19 19:04
@dansiegel Also, I have a question regarding the preferred choice of container. I see that when a new project is created, Dryloc is selected by default. Does that mean you encourage people to use it for XF instead of the other ones?

**Comment by dansiegel** [comment] 2018-05-20 00:26
@scxp thanks for the feedback, I'll take some of that into consideration as I update the templates

> In both files, RegisterTypes is expecting a parameter named container even though IPlatformInitializer is expecting containerRegistry. (Observe that App.xaml.cs is also using containerRegistry)

Realistically it can be named anything you want. I agree it should be updated to containerRegistry, but don't mistake that for it being a requirement, it's not... it's only a requirement that the type is IContainerRegistry, otherwise you wouldn't have implemented the interface. The name `containerRegistry` is more of a convention.

> In MainActivity.cs, Prism is setting Android icon to @mipmap/ic_launcher, but XF sets it to @mipmap/icon

That is because the icon filename is ic_launcher which is actually the correct naming (see the [Android Guidelines](https://developer.android.com/guide/practices/ui_guidelines/icon_design). For both Android and iOS you'll find that the icons were generated from https://makeappicon.com/ which is correctly generating icons for iOS and Android... and Assets.xcassets is the newer way of bundling icons and the way [Apple wants them bundled](https://stackoverflow.com/questions/38117076/asset-catalog-vs-folder-reference-when-to-use-one-or-the-other)... AFAIK Xamarin has never updated their templates to use it. However, if you were to use Xcode this is what you're going to get rather than a Resources folder to dump images into. 

> I see that when a new project is created, Dryloc is selected by default. Does that mean you encourage people to use it for XF instead of the other ones?

Officially we do not suggest that you use any specific container. DryIoc does however have the best performance according to the [benchmarks](http://www.palmmedia.de/blog/2011/8/30/ioc-container-benchmark-performance-comparison) which is one of the reasons why I personally use it as my go to container. The fact that Unity had no maintainers for about 2 years had a lot to do with us to changing the default. Really the only guidance I would officially give you is that if you are using Modules (which I suggest you do) then you do not want to use Autofac as Modularity requires a mutable container which Autofac is not.

**Comment by scxp** [comment] 2018-05-20 01:56
Thanks for the response! I agree about `containerRegistry` being a convention, and I listed it hoping that platform-specific declarations would follow the rest of the convention. :) I did not know all that about icons and Assets. Thanks for the clarification. I was simply comparing Xamarin to Prism. Also thanks for the benchmarks. Seems like Dryloc is indeed quite fast. :)

**Comment by brianlagunas** [comment] 2018-05-21 14:04
The Prism Template pack will be updated when we release the next version of Prism.

**Comment by adrianknight89** [comment] 2018-05-21 16:02
@brianlagunas Awesome. Thanks for your work, guys!

**Comment by TedMobile** [comment] 2018-06-28 06:08
Hi any update on when the latest prism template pack will be released.thanks

**Comment by dansiegel** [comment] 2018-06-28 06:12
The latest update is available now for Visual Studio Mac... an update for Visual Studio 2017 will likely come out some time in July... sorry I cannot be more specific.

**Comment by chrisgate** [comment] 2018-07-20 10:40
I am feeling jealous bcoz every-time Windows User will always wait...........especially since @dansiegel and  Visual Studio Mac are same.
Can we always delay one for others so that we access to all inrespecitive of platform.Thanks

copy @brianlagunas @bartlannoeye

**Comment by lewcianci** [comment] 2018-08-16 21:54
@dansiegel @brianlagunas Is the template studio for mac open source?  If so, where is it stored? I'd like to build a web app that generates the templates that a user can download and use on their visual studio, mac or windows.

The VS4MAC template studio is absolutely incredible but maintaining two seperate platform wizards (mac and windows) with two seperate codebases, as well as maintaining the prism codebase, plus doing your day jobs, must be a crippling amount of work for you to do :(.

FWIW your framework makes Xamarin programming possible, and even enjoyable.

**Comment by dansiegel** [comment] 2018-08-16 22:13
@lewcianci I appreciate the kind words. The templates are currently closed source. There was never really any community involvement on them unfortunately and particularly with the IDE integration that we now have in VS Mac (which I will be adding to VS 2017) there is some stuff in there that we prefer to keep closed source for the foreseeable future.

As you pointed out it is an incredible amount of work maintaining everything about Prism + Day Jobs + Family + some pretending to have a life outside of all of that.... We really appreciate any support members of the community are able to provide whether it's a personal contribution as a [Prism Patron](https://www.patreon.com/prismlibrary), or if your company is willing to make a more substantial donation, it really does help us out.

As for your goal of generating a web app why don't you ping me on [Twitter](https://twitter.com/DanJSiegel) and we can set up some time to do a conference call. Technically speaking all of our Templates are the exact same on Mac and PC as we've migrated to the new dotnet templates. I used to ship the Quick Start Templates via NuGet and could start doing that again if I see some interest in people who want to use the CLI to generate projects.

**Comment by TedMobile** [comment] 2018-08-23 07:46
@dansiegel 
Hi there I am going to push the company I work for to become a Prism patron.Manager is on hols at the moment. 

Side note
Prism made building an app easier ,however you guys might be victim of your own success with prism for xamarin as so many people use it now.

Is there a chance of slightly more frequent update? 
Any ideas at this stage when then Windows template will be released?

I know and I understand it's free and its own time but some sort of update will be nice.

Many thanks for your effort

**Comment by chrisgate** [comment] 2018-08-23 07:57
@dansiegel  " I used to ship the Quick Start Templates via NuGet and could start doing that again if I see some interest in people who want to use the CLI to generate projects."
You know people will be so please to have the CLI.............my testimony: that CLI made me to know prism use case fast and that quickly jumpstart my career in Mobile world............i am Prism patron by the way.

Cheers

**Comment by brianlagunas** [comment] 2018-08-23 15:00
@TedMobile we have integration builds that are published to our MyGet feed on every build we do. That's about as updated as you can get :)

**Comment by dansiegel** [comment] 2018-08-23 19:56
@TedMobile 
> Is there a chance of slightly more frequent update?

We generally try to get new updates out when there is something significant for us to update. This could be new features, bug fixes, or Prism GA releases. While I consider Prism 7.1 to be stable to use in Production for Xamarin.Forms apps, I still believe that targeting the Preview should be an opt-in feature. It's possible in the future that we may enable that as an option in the QuickStart templates but for now it'll have to be on the backlog

> Any ideas at this stage when then Windows template will be released?

I assume you're referring to the QuickStart Templates and tooling we have for VS Mac. I'll actually be starting work on that this month... We'll likely have some previews starting next month for Platinum Patrons. If you're referring to UWP Templates that won't come until after we've dealt with PR #1513 


@chrisgate I'll look at doing some refactoring to start generating a usable artifact I can publish. The problem is that in order to make the CI a bit easier I stopped versioning the NuGet, so I'll have to figure out a Versioning schema and then I think we can make all of the Prism Templates available.

**Comment by TedMobile** [comment] 2018-08-24 06:28
First thanks for your time and reply!

@brianlagunas 
you are right I could use the myget feed and I do ,but my manager is against things that are not "proper" releases and therefore wont let me use it for production when they are in preview.

@dansiegel 
yes I am referring to the quick start templates and tooling you have for mac to be available for windows as well.

I would like to say that I am an happy prism user and again I will try to make may company to be a patron.

Do you guys have some sort of roadmap for Prism apart from bugfixes ?
Are there any plans for new functionalities ,automation-video-samples. etc..?
Will it be something like "Weekly xamarin" or may be even a monthly newsletter or something
Is this all part of the patron concept? 

thanks again for your fantastic work

**Comment by brianlagunas** [comment] 2018-08-24 14:32
If that's the case, then you'll just have to wait until we have time to do an official release.

We do not have official roadmaps. We squeeze Prism in when we have time between our demanding day jobs, family time, and sleep.  It's coming slow, but we are almost at a point where we can release 7.1. We are targeting Oct for a 7.1 release.

**Comment by brianlagunas** [comment] 2018-09-24 20:42
The Prism Template Pack has been updated with the latest preview updates and is available on the Patreon site for Platinum patrons. 

https://www.patreon.com/prismlibrary

When Prism 7.1 is released as RTM in Oct, the Prism Template Pack will be made available on the Visual Studio Marketplace.

**Closed by brianlagunas** 2018-09-24 20:42 UTC
Labels: Template Pack, XF
