### ISSUE TITLE
Memory leak with Prism Region listeners

### ISSUE THREAD

**Issue by dkofoed** [PrismLibrary/Prism#1183] opened 2017-10-02 21:19 UTC
### Package info

- Platform: Windows 10
- Prism version: 6.2.0.0
- Xamarin version (if applicable):
- Windows 10 SDK version (if applicable):
- Other version info:

### Repro steps

We have a scenario in which we are using Prism at a feature level.  The Prism "shell" is actually a user control that is hosted inside consuming applications.  What we noticed is that when the shell control was reloaded, the load times increased gradually due to a memory leak with the region listeners.  Multiple regions are being populated during load, and each of those regions is holding onto a listener instance and they don't ever appear to be removed.

We modified the source code to remove all listeners and the issue was resolved in local testing.  We'd like to request a fix for this to remove all region listeners inside RegionManager.cs.

**Comment by brianlagunas** [comment] 2017-10-02 22:45
I am assuming your platform is WPF and not Windows 10.  If you believe you have found a memory leak, please provide a sample that reproduces it along with a memory profiler that can identify the object rooting the views.  I don't know what "shell control was reloaded" means, but that can mean many things and you may have application code that is causing this behavior.

99% of the time, a memory leak has been application code.  I am closing this until it can be reproduced and verified.

**Closed by brianlagunas** 2017-10-02 22:45 UTC
Labels: WPF

**Comment by dkofoed** [comment] 2017-10-04 00:37
Attaching zip file containing sample app and ANTS profiler results.  

[SamplePrism6.2.0.zip](https://github.com/PrismLibrary/Prism/files/1354294/SamplePrism6.2.0.zip)

**Comment by brianlagunas** [comment] 2017-10-04 01:11
Base on the code you provided in your duplicate issue #1188, this is a result of poor coding practices.  For one, NEVER create multiple bootstrappers.  A Prism projects has only one Bootstrapper.  You are also using an implicit data template for all tabs you are adding.  This is really slow in general and not recommended, especially since you are wanting to use scoped regions (DataTemplates don't support scoped regions).  You are registering a view as a singleton which is not recommended. Prism handles instances for you.

The memory profile also shows that Prism is not rooting your app.  It's your code.  You can eliminate the root simply by commenting out your code in the `ExecuteTabChange` method lines 40-57. 

This is extremely overly complicated and breaks just about every best practice there is.  Please look at the WPF samples on how you should be using Prism.

**Comment by brianlagunas** [comment] 2017-10-04 01:15
This course might help you https://www.pluralsight.com/courses/prism-mastering-tabcontrol

**Comment by dkofoed** [comment] 2017-10-04 18:11
Thanks for the response ... couple follow up questions:

1) What are you referring to when you say "multiple bootstrappers"?  There's only one in the sample app we sent.

2) We can't comment out the code in the ExecuteTabChange method as no content is loaded in that case.  That logic is performing a "navigation" to essentially load the content of the tab when the tab is selected since we do not want to load all content for all tabs during the initial load of the tab control (i.e. lazy loading).  We initially were using view injection but changed to the navigation approach.

3) We've watched the majority of your Prism presentations already, including the Tab Control one that you recommended.  The tab control course is great, however doesn't showcase the same scenario, as we need all tabs to load at once - not on demand.  The sample we sent is our general approach to that (including lazy loading of the actual tab content upon selection), however if you think there's a better way to achieve all that with Prism, would it be possible to upload a sample demonstrating that?

Cheers!

**Comment by brianlagunas** [comment] 2017-10-04 18:15
1. you are creating multiple instaces of the bootstrapper. A lot of initialization happens in there and should only occur once in an app domain
2. Yes you can.  You are taking a bad approach to navigating within your scoped regions.
3. If you would like to pay for my consulting time, I would gladly show you how to achieve the same thing without the memory leak.
