### ISSUE TITLE
Prism.Windows - Service state service failed exception

### ISSUE THREAD

**Issue by aakansha** [PrismLibrary/Prism#333] opened 2015-12-04 12:31 UTC
Hi,

I am getting exception in Prism.Windows when I build my code in Release mode with .Net Native Compilation. The scenario is when I trigger Suspend mode in application, I get exception in SessionStateService.cs in SaveAsync() function. The exception is 

**Exception thrown: 'Prism.Windows.AppModel.SessionStateServiceException' in Prism.Windows.dll
Additional information: Session state service failed**

Note - This application does not throw any exception if .Net native Compilation is not on. I also noticed that the parameter _sessionState has different no of parameters when .Net Native Compilation is different in both the modes.

**Comment by bartlannoeye** [comment] 2015-12-04 12:48
Hey @aakansha, welcome to our repo. I haven't had time to check further into your [StackOverflow](http://stackoverflow.com/questions/34062780/session-state-service-failed-uwp) question. Thanks for logging it here as well so we don't forget it, we'll update both.

To be checked if this is a Prism bug or some error in the app.

**Comment by aakansha** [comment] 2015-12-04 12:53
Hi Bart,

Sure. According to my research there is some problem with Serialization in Prism codebase with .NET Native Compilation is done. Let me know what more info I can provide you with.

Thanks in advance for help.

**Comment by Riessfelt** [comment] 2015-12-10 20:03
Hello. It looks like I am facing the same problem(Suspension does not work with .net native enabled). When I try to suspend my UWP application I get an exception:

Exception name: Prism.Windows.AppModel.SessionStateServiceException
Message: "Session state service failed"
Stacktrace: "   at Prism.Windows.AppModel.SessionStateService.<SaveAsync>d__5.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\\dd\\ndp\\fxcore\\src\\System.Private.CoreLib\\System\\Runtime\\ExceptionServices\\ExceptionDispatchInfo.cs:line 66\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\\dd\\ndp\\fxcore\\src\\System.Private.Threading\\System\\Runtime\\CompilerServices\\TaskAwaiter.cs:line 186\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\\dd\\ndp\\fxcore\\src\\System.Private.Threading\\System\\Runtime\\CompilerServices\\TaskAwaiter.cs:line 155\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) in f:\\dd\\ndp\\fxcore\\src\\System.Private.Threading\\System\\Runtime\\CompilerServices\\TaskAwaiter.cs:line 127\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in f:\\dd\\ndp\\fxcore\\src\\System.Private.Threading\\System\\Runtime\\CompilerServices\\TaskAwaiter.cs:line 112\r\n   at Prism.Windows.PrismApplication.<OnSuspending>d__61.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\\dd\\ndp\\fxcore\\src\\System.Private.CoreLib\\System\\Runtime\\ExceptionServices\\ExceptionDispatchInfo.cs:line 66\r\n   at System.Threading.Tasks.ExceptionDispatchHelper.<>c__DisplayClass0.<ThrowAsync>b__1(Object edi) in f:\\dd\\ndp\\fxcore\\src\\System.Runtime.WindowsRuntime\\System\\Threading\\Tasks\\ExceptionDispatchHelper.cs:line 28\r\n   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() in f:\\dd\\ndp\\fxcore\\src\\System.Private.Threading\\System\\Threading\\SynchronizationContext.cs:line 181"

InnerException: System.Runtime.Serialization.InvalidDataContractException
Message: "SerializationCodeIsMissingForType. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485"
Stacktrace: "   at System.Runtime.Serialization.DataContract.GetDataContractFromGeneratedAssembly(Type type)\r\n   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)\r\n   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)\r\n   at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type, SerializationMode mode)\r\n   at System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract(RuntimeTypeHandle typeHandle, Type type)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType(XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle objectTypeHandle, Type objectType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, Type declaredType)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize(XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerializeReference(XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle)\r\n   at Type93.WriteKeyValueOfstringanyTypeToXml(XmlWriterDelegator A_0, Object A_1, XmlObjectSerializerWriteContext A_2, ClassDataContract A_3)\r\n   at System.Runtime.Serialization.XmlFormatCollectionWriterDelegate.InvokeOpenStaticThunk(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, CollectionDataContract dataContract)\r\n   at System.Runtime.Serialization.XmlFormatClassWriterDelegate.Invoke(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, ClassDataContract dataContract)\r\n   at System.Runtime.Serialization.ClassDataContract.WriteXmlValue(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context)\r\n   at Type90.WriteArrayOfKeyValueOfstringanyTypeToXml(XmlWriterDelegator A_0, Object A_1, XmlObjectSerializerWriteContext A_2, CollectionDataContract A_3)\r\n   at System.Runtime.Serialization.XmlFormatCollectionWriterDelegate.InvokeOpenStaticThunk(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, CollectionDataContract dataContract)\r\n   at System.Runtime.Serialization.XmlFormatClassWriterDelegate.Invoke(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, ClassDataContract dataContract)\r\n   at System.Runtime.Serialization.CollectionDataContract.WriteXmlValue(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, Boolean verifyKnownType, RuntimeTypeHandle declaredTypeHandle, Type declaredType)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType(XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle objectTypeHandle, Type objectType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, Type declaredType)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize(XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerializeReference(XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle)\r\n   at Type93.WriteKeyValueOfstringanyTypeToXml(XmlWriterDelegator A_0, Object A_1, XmlObjectSerializerWriteContext A_2, ClassDataContract A_3)\r\n   at System.Runtime.Serialization.XmlFormatCollectionWriterDelegate.InvokeOpenStaticThunk(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, CollectionDataContract dataContract)\r\n   at System.Runtime.Serialization.XmlFormatClassWriterDelegate.Invoke(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, ClassDataContract dataContract)\r\n   at System.Runtime.Serialization.ClassDataContract.WriteXmlValue(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context)\r\n   at Type90.WriteArrayOfKeyValueOfstringanyTypeToXml(XmlWriterDelegator A_0, Object A_1, XmlObjectSerializerWriteContext A_2, CollectionDataContract A_3)\r\n   at System.Runtime.Serialization.XmlFormatCollectionWriterDelegate.InvokeOpenStaticThunk(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, CollectionDataContract dataContract)\r\n   at System.Runtime.Serialization.XmlFormatClassWriterDelegate.Invoke(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, ClassDataContract dataContract)\r\n   at System.Runtime.Serialization.CollectionDataContract.WriteXmlValue(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, Boolean verifyKnownType, RuntimeTypeHandle declaredTypeHandle, Type declaredType)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType(XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle objectTypeHandle, Type objectType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, Type declaredType)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize(XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerializeReference(XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle)\r\n   at Type93.WriteKeyValueOfstringanyTypeToXml(XmlWriterDelegator A_0, Object A_1, XmlObjectSerializerWriteContext A_2, ClassDataContract A_3)\r\n   at System.Runtime.Serialization.XmlFormatCollectionWriterDelegate.InvokeOpenStaticThunk(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, CollectionDataContract dataContract)\r\n   at System.Runtime.Serialization.XmlFormatClassWriterDelegate.Invoke(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, ClassDataContract dataContract)\r\n   at System.Runtime.Serialization.ClassDataContract.WriteXmlValue(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context)\r\n   at Type90.WriteArrayOfKeyValueOfstringanyTypeToXml(XmlWriterDelegator A_0, Object A_1, XmlObjectSerializerWriteContext A_2, CollectionDataContract A_3)\r\n   at System.Runtime.Serialization.XmlFormatCollectionWriterDelegate.InvokeOpenStaticThunk(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, CollectionDataContract dataContract)\r\n   at System.Runtime.Serialization.XmlFormatClassWriterDelegate.Invoke(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, ClassDataContract dataContract)\r\n   at System.Runtime.Serialization.CollectionDataContract.WriteXmlValue(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)\r\n   at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)\r\n   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)\r\n   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)\r\n   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)\r\n   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)\r\n   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(Stream stream, Object graph)\r\n   at Prism.Windows.AppModel.SessionStateService.<SaveAsync>d__5.MoveNext()"

Steps to reproduce:
1). Clone this git repo https://bitbucket.org/TocoToucan/myanimelistrt . You can remove stuff like third party Syncfusion controls because they are not related to this problem.
2). Debug it with .net native enabled.
3). Click "Suspend and shutdown" in VS.

Additional info:
1). Without .net native suspension works ok.
2). Test account for my app: MyanimelistRT/headhunterRT

**Comment by bartlannoeye** [comment] 2015-12-10 22:24
Thanks for the repro, we'll try to have a look at it as soon as possible.

**Comment by 505aaron** [comment] 2015-12-15 19:43
I have hit the same problem and I believe it is due to the runtime definition file missing types serialized by the SessionStateService. I'll add a comment if I can determine which declarations are required for Prism to work with native compilations.

See here https://msdn.microsoft.com/en-us/library/dn600639%28v=vs.110%29.aspx

**Comment by 505aaron** [comment] 2015-12-16 17:03
As I a workaround I created my own SessionStateService implementation that uses JSON.Net library instead of DataContractSerializer. I exposed my known serialized types in the runtime definition file. 

Here is the implementation of SaveAsync and RestoreSessionStateAsync
```csharp
 /// <summary>
        /// Save the current <see cref="SessionState"/>. Any <see cref="Frame"/> instances
        /// registered with <see cref="RegisterFrame"/> will also preserve their current
        /// navigation stack, which in turn gives their active <see cref="Page"/> an opportunity
        /// to save its state.
        /// </summary>
        /// <returns>An asynchronous task that reflects when session state has been saved.</returns>
        public async Task SaveAsync()
        {
            try
            {
                // Save the navigation state for all registered frames
                foreach (var weakFrameReference in _registeredFrames)
                {
                    IFrameFacade frame;
                    if (weakFrameReference.TryGetTarget(out frame))
                    {
                        SaveFrameNavigationState(frame);
                    }
                }

                JsonSerializer serializer = new JsonSerializer
                {
                    TypeNameHandling = TypeNameHandling.All,
                    DateFormatHandling = DateFormatHandling.IsoDateFormat,
                    DateTimeZoneHandling = DateTimeZoneHandling.Utc,
                };

                // Serialize the session state synchronously to avoid asynchronous access to shared
                // state
                using (MemoryStream sessionData = new MemoryStream())
                using (var jsonTextWriter = new JsonTextWriter(new StreamWriter(sessionData)))
                {
                    serializer.Serialize(jsonTextWriter, _sessionState);

                    // Flush to the underyling stream.
                    jsonTextWriter.Flush();

                    // Get an output stream for the SessionState file and write the state asynchronously
                    StorageFile file =
                        await
                            ApplicationData.Current.LocalFolder.CreateFileAsync(SessionStateFileName,
                                CreationCollisionOption.ReplaceExisting);
                    using (var fileStream = await file.OpenAsync(FileAccessMode.ReadWrite))
                    {
                        sessionData.Seek(0, SeekOrigin.Begin);
                        var provider = new DataProtectionProvider("LOCAL=user");

                        // Encrypt the session data and write it to disk.
                        await provider.ProtectStreamAsync(sessionData.AsInputStream(), fileStream);
                        await fileStream.FlushAsync();
                    }
                }
            }
            catch (Exception e)
            {
                throw new SessionStateServiceException(e);
            }
        }

        /// <summary>
        /// Restores previously saved <see cref="SessionState"/>.
        /// </summary>
        /// <returns>An asynchronous task that reflects when session state has been read. The
        /// content of <see cref="SessionState"/> should not be relied upon until this task
        /// completes.</returns>
        public async Task RestoreSessionStateAsync()
        {
            _sessionState = new Dictionary<String, Object>();

            try
            {
                JsonSerializer serializer = new JsonSerializer
                {
                    TypeNameHandling = TypeNameHandling.All,
                    DateFormatHandling = DateFormatHandling.IsoDateFormat,
                    DateTimeZoneHandling = DateTimeZoneHandling.Utc,
                };

                // Get the input stream for the SessionState file
                StorageFile file = await ApplicationData.Current.LocalFolder.GetFileAsync(SessionStateFileName);

                using (IInputStream inStream = await file.OpenSequentialReadAsync())
                using (var memoryStream = new MemoryStream())
                {
                    var provider = new DataProtectionProvider("LOCAL=user");

                    // Decrypt the prevously saved session data.
                    await provider.UnprotectStreamAsync(inStream, memoryStream.AsOutputStream());
                    memoryStream.Seek(0, SeekOrigin.Begin);

                    using (var reader = new JsonTextReader(new StreamReader(memoryStream)))
                    {
                        // Deserialize the Session State
                        _sessionState = serializer.Deserialize<Dictionary<string, object>>(reader);
                    }
                }
            }
            catch (Exception e)
            {
                throw new SessionStateServiceException(e);
            }
        }
```
Here is a sample runtime definition file
```xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
    <!--
      An Assembly element with Name="*Application*" applies to all assemblies in
      the application package. The asterisks are not wildcards.
    -->
    <Assembly Name="*Application*" Dynamic="Required All" />

    <!-- Add your application specific runtime directives here. -->
    <Namespace Name="Models" Serialize="Required PublicAndInternal">
      <Type Name="MyModelClass" Browse="Required Public" Serialize="Public"/>
   </Namespace>
  </Application>
</Directives>
```

**Comment by Riessfelt** [comment] 2015-12-24 17:50
Why did you add "to verify" label without doing any issue related commits?

**Comment by brianlagunas** [comment] 2015-12-24 19:27
Because "to verify" means we have to verify the issue first before we can start working on a fix.

**Comment by bartlannoeye** [comment] 2016-01-02 22:32
I've built a repro in [this branch](https://github.com/bartlannoeye/Prism/tree/Serialization) to try some things out on the serialization. Looks like everything can be fixed with runtime directives and there's no need for a new SessionStateService with JSON.NET.

     <Namespace Name="HelloWorld.Models" Serialize="Required PublicAndInternal">
       <Type Name="MyModel" Browse="Required Public" DataContractSerializer="Required Public"/>
     </Namespace>
 
@aakansha @Riessfelt @505aaron, could you please check if setting the DataContractSerializer attribute in the rd.xml file fixes your issues as well?

I'll write a blog post and some documentation on this tomorrow.

**Comment by Riessfelt** [comment] 2016-01-03 11:55
I modified my Default.rd.xml and decorated types/properties using [DataContract] and [DataMember] attributes. It didn't solve my problem, still the same session state related exception.
Btw, I am not sure that my Default.rd.xml file is correct. You can view its content here http://pastebin.com/iCZBxLp3

**Comment by bartlannoeye** [comment] 2016-01-04 18:51
It seems good on first sight, haven't built your project though as it has several dependencies I don't have installed. I'd suggest building a small app and try out your models one by one to find the culprit. On the other hand, since you use sqlite, I'm not sure it's necessary to store everything in the session state, I'd just retrieve it from sqlite again.

**Comment by aakansha** [comment] 2016-01-05 16:24
@Riessfelt - I would suggest to debug your code by including Prism codebase from github. When you are debugging with the codebase, you will get the exact error with missing types. The exception will tell you which types need to be added in default.rd.xml. I initially started debugging this way and fixed my issue. In my scenario, I had several dependencies too which made it difficult to figure out where is the exact issue. You will get exception in SaveAsync() function of Prism codebase. 

I later realized that rather than adding list of all explicit list of types, we could do something like as shown below. Since we already know that we want to be able to serialize everything that gets passed into SessionStateService.RegisterKnownType, we can write a directive that looks like this:
```
<Type Name=”Prism.Windows.AppModel.SessionStateService”>
    <Method Name=”RegisterKnownType”>
        <TypeParameter Name=”type” DataContractSerializer=”Required All” />
    </Method>
</Type>
```
Any type passed as the parameter named “type” to RegisterKnownType will be serialized. 

@bartlannoeye - I do have one question. Previously, we used to override OnRegisterKnownTypesForSerialization function to tell list of known types for the SuspensionManager in app.xaml.cs and add all RegisterKnownType in it.  

My question is what will be the effect if I don't override this function anymore in the app.xaml.cs since I already have added all the types in default.rd.xml??

**Comment by kobush** [comment] 2016-01-20 15:09
I just run into the very same problem. After I suspend and terminate the app, and then try to reasume I get this error. 

Exception thrown: 'System.Runtime.Serialization.InvalidDataContractException' in System.Private.DataContractSerialization.dll
Additional information: SerializationCodeIsMissingForType. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485

From the above conversation I'm not clear whats the current state of this issue. Is this fixed and I should get latest from GitHub? Or should I use the workaround with Json serialilzer?

**Comment by brianlagunas** [comment] 2016-01-20 15:53
We haven't made any progress on the serialization issue.

**Comment by Shinoa-best-girl** [comment] 2016-02-15 21:26
Do you guys have any progress? The problem is still actual.

**Comment by chendu4u** [comment] 2016-03-09 08:36
Any update on this issue 

Message = "Session state service failed"

 InnerException = {"Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))"}

   at Prism.Windows.AppModel.SessionStateService.<SaveAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Prism.Windows.PrismApplication.<OnSuspending>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

**Comment by bartlannoeye** [comment] 2016-03-09 09:30
We're currently too flooded with other work to go through this issue history and double check everything to close it. The initial issue was fixed by adding a line to the .rd.xml file (see http://stackoverflow.com/questions/34062780/session-state-service-failed-uwp)

I hope to have some spare time in the upcoming weeks to finally close this down.

**Comment by PrakashSSV** [comment] 2016-03-17 08:23
cannot inherit from a type that is not marked with DataContractAttribute or SerializableAttribute.  Consider marking the base type 'Prism.Windows.Mvvm.ViewModelBase' with DataContractAttribute or SerializableAttribute, or removing them from the derived type.

**Comment by brianlagunas** [comment] 2016-03-17 15:23
This probably won't happen due to the reasons discussed in this post: https://github.com/PrismLibrary/Prism/issues/57

**Comment by boodoolak** [comment] 2016-04-27 08:49
I solve this problem. I'm beginner, therefore sorry for my code)
I'm replace 

    _sessionStateService.SessionState["TripsListToday"] = TripsListToday; //TripsListToday is complex class

on 
    
    _sessionStateService.SessionState["TripsListToday"] = JsonConvert.SerializeObject(TripsListToday);

And read it:

        public override void OnNavigatedTo(NavigatedToEventArgs e, Dictionary<string, object> viewModelState)
        {
            base.OnNavigatedTo(e, viewModelState);

            if (_sessionStateService.SessionState.ContainsKey("TripsListToday"))
            {
                if (!string.IsNullOrEmpty(_sessionStateService.SessionState["TripsListToday"] as string))
                {
                    TripsListToday = JsonConvert.DeserializeObject<ObservableCollection<Trip>>(_sessionStateService.SessionState["TripsListToday"].ToString());
                }
            }
        }

This is workaround, but it work.

**Comment by artemious7** [comment] 2017-02-19 18:36
I added this to my Default.rd.xml and it worked.

```
<Namespace Name="MyNamespace.PagePayloads" 
                      Serialize="Required PublicAndInternal"
                      Browse="Required Public"
                      DataContractSerializer="Required Public" />
```

The namespace "MyNamespace.PagePayloads" contains all the types that are serialized by Prism when Suspending.

**Comment by brianlagunas** [comment] 2017-10-06 17:25
This issue has been resolved on SO. https://stackoverflow.com/questions/34062780/session-state-service-failed-uwp

**Closed by brianlagunas** 2017-10-06 17:25 UTC
Labels: to verify, UWP
