### ISSUE TITLE
[XF] Issue with OnNavigatedTo in Modal push

### ISSUE THREAD

**Issue by CarMatt** [PrismLibrary/Prism#460] opened 2016-02-15 18:34 UTC
Is this a known issue that  - "OnNavigatedTo" not fire after coming back from a modal page?
It applies only to iOS, droid works.

Or have I missed something when it comes to "GoBack" in modal navigation?

**Comment by brianlagunas** [comment] 2016-02-15 18:55
Are you using the latest 6.1.0 Preview 3?

**Comment by CarMatt** [comment] 2016-02-15 19:17
Yes we do,

Prism.Core 6.1.0
Prism.Unity 6.2.0-pre3
Prism.Forms 6.1.0-pre3

And latest stabile Xamarin.Forms

Just realized that we only tested on the simulator for iOS, it might have something to do with it? Will test a device soon

**Comment by brianlagunas** [comment] 2016-02-15 19:31
Are you calling NavigationService.GoBack(), or are you simply hitting the built-in software button?

**Comment by CarMatt** [comment] 2016-02-15 19:36
Yes, NavigationService.GoBack().
```
        public PrismContentPage2ViewModel(INavigationService navigationService)
        {
            _navigationService = navigationService;
            PopDelegateCommand = new DelegateCommand(Pop);

        }

        private void Pop()
        {
            NavigationParameters parameters = new NavigationParameters();
            parameters.Add("key2", "value2");
            _navigationService.GoBack(parameters, true);
     
        }
```

**Comment by brianlagunas** [comment] 2016-02-15 19:50
Weird.  Can you provide a simple repo that I can run to debug?

**Comment by CarMatt** [comment] 2016-02-15 19:58
Super, providing you soon

**Comment by CarMatt** [comment] 2016-02-15 22:37
-->[Git](https://github.com/CarMatt/PrismNavi)
Have tested again and it works on droid but not in iOS. However, have not tested the iOS device yet (only iOS simulator)

**Comment by brianlagunas** [comment] 2016-02-16 01:11
Yup, duplicated it with your repro.  I'll dig into this and see why iOS is being a pain in the ass.

**Comment by brianlagunas** [comment] 2016-02-16 01:52
Found the issue!  It seems iOS and Android handle the modal navigation stack differently.  Uggggg!!!  I'll work on fixing this one.

**Comment by brianlagunas** [comment] 2016-02-16 02:09
So it appears this is something I can't fix.  I am going to ask Xamarin why iOS behaves this way and if it is either a bug on their side, or if there is a work around that I can use.  I'll keep you posted.

**Comment by CarMatt** [comment] 2016-02-16 09:14
Thx Brian, like your fast feedback!

**Comment by brianlagunas** [comment] 2016-02-24 20:55
This is a confirmed Xamarin.Forms bug.  You can follow the status here:

https://bugzilla.xamarin.com/show_bug.cgi?id=39104

I will update this issue when this has been resolved by Xamarin.  This seems to be limited to the initial MainPage so all other GoBack calls will work as expected.

**Comment by brianlagunas** [comment] 2016-03-16 15:16
This has been fixed by Xamarin.  Should be available in 2.2.0-pre1

**Closed by brianlagunas** 2016-03-16 15:16 UTC
Labels: bug, XF

**Comment by CarMatt** [comment] 2016-03-25 21:20
Good news! See you at //Build next week =)

**Comment by brianlagunas** [comment] 2016-03-25 21:34
Sweet!  Be sure to find me and say hello.
