### ISSUE TITLE
[BUG] Absolute navigation not working on iOS

### ISSUE THREAD

**Issue by nk-alex** [PrismLibrary/Prism#3166] opened 2024-06-14 13:31 UTC
### Description

After I login in my application, I want to remove my LoginPage from stack and just have my MainPage. On Android, I ahieve this by using absolute navigation:

`await NavigationService.NavigateAsync("/MainPage");`

But this is not working on iOS. LoginPage is still on my navigation stack and MainPage is not showing. I even tried with 

`await NavigationService.NavigateAsync("../MainPage");`

but same result.

### Steps to Reproduce

- Create new project with two pages. 
- On PrismStartup, on Configure method, show FirstPage on start : `builder.RegisterTypes(RegisterTypes).OnAppStart("FirstPage");`
- Put a button on FirstPage. On clicked, try to absolute navigate to the second page from first one: `await NavigationService.NavigateAsync("/SecondPage");`
- This will clear the navigation stack and put SecondPage on the clear stack on Android. On iOS, nothing will happen

### Platform with bug

.NET MAUI

### Affected platforms

iOS

**Comment by brianlagunas** [comment] 2024-06-14 13:38
Reproduction apps are required. Closing this issue until one is provided.

**Comment by dansiegel** [comment] 2024-07-04 03:43
This is not a bug and works just fine if you use even the latest public version of Prism.Maui.

**Closed by dansiegel** 2024-07-04 03:43 UTC
Labels: bug, invalid
