### ISSUE TITLE
[Bug] How does the dryioc container fit into iservicelocator in the latest version 8.0

### ISSUE THREAD

**Issue by LostAsk** [PrismLibrary/Prism#2231] opened 2020-10-30 07:05 UTC
In version 7.2, the configureservicelocator method in prismapplicationbase is injected into iservicelocator,

However, in version 8, this method was canceled. How to inject into iservicelocator for compatibility with previous versions

**Comment by brianlagunas** [comment] 2020-10-30 14:34
Closing as this is not a bug, and questions do not belong as issues.

**Closed by brianlagunas** 2020-10-30 14:34 UTC
Labels: bug, to verify
