### ISSUE TITLE
Prism 7.1.0.431 is missing Prism.Navigation in the net45 dll

### ISSUE THREAD

**Issue by jahmai** [PrismLibrary/Prism#1687] opened 2019-02-11 02:49 UTC
### Description

The .net version of Prism.dll is missing the whole Navigation namespace. So if you build against netstandard prism and then try to use classes that depend on that namespace in a net45 application it'll crash.

### Steps to Reproduce

1. Create an object that references INavigationAware in a new netstandard library
2. Reference the netstandard library in a net45 application
3. Instantiate the object in the net45 application
4. Run the application

### Expected Behavior

The application runs without error

### Actual Behavior

The application throws: System.TypeLoadException: 'Could not load type 'Prism.Navigation.INavigationAware' from assembly 'Prism, Version=7.1.0.431, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59'.'

### Basic Information

- Version with issue:
- Last known good version: 7.0.0.396
- Xamarin.Forms version: 
- IDE: VS 2017 15.9.5

### Reproduction Link

https://www.dropbox.com/s/idejvwnsb1jvbs2/BadPrism.zip?dl=0

**Comment by bartlannoeye** [comment] 2019-02-11 09:06
Got removed in https://github.com/PrismLibrary/Prism/commit/4a1e14335b7abb874ee1de54a0682573f3c112db#diff-b65c4362e0a8b3ac9dfdd12b95932d85

@brianlagunas could you check please?

**Comment by dansiegel** [comment] 2019-02-11 13:54
This is by design. Closing as duplicate see #1664 for more information

**Closed by dansiegel** 2019-02-11 13:54 UTC

**Comment by jahmai** [comment] 2019-02-11 23:10
This is silly and breaks tools like MEF that do assembly type scanning. Even if the code resides in a shared library that isn't used in WPF it will break and .net application that uses the library in a reflection scanning capacity.

**Comment by brianlagunas** [comment] 2019-02-11 23:13
You are more than welcome to fork Prism, and remove that limitation yourself.

**Comment by jahmai** [comment] 2019-02-11 23:14
I'm well aware of what can be achieved with open source applications, thanks for the tip though.

**Comment by WarBorg** [comment] 2019-08-27 21:04
the problem I am facing now is that I inject the navigation service in my view models and the Unit Tests written for those viewmodels do not compile anymore since the Unit Test project has the target set to .Net 4.7.2 and it does not recognise the the INavigationService anymore.

Any ideas on how to solve this ?

**Comment by WarBorg** [comment] 2019-08-28 20:30
@brianlagunas tried that, but when I run the test I get an error from the test: (this is with .NET Core 2.1)

```System.TypeLoadException : Could not load type 'Prism.Navigation.INavigationAware' from assembly 'Prism, Version=7.2.0.1367, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59'.```

**Comment by dansiegel** [comment] 2019-08-29 02:05
@WarBorg you need to have everything on the same version. In 7.2 we moved the navigation interfaces back to Prism.Forms so it is available regardless of what TFM you are using for your tests
