### ISSUE TITLE
Prism 7 does not build

### ISSUE THREAD

**Issue by robertwharvey** [PrismLibrary/Prism#1660] opened 2019-01-12 16:42 UTC
### Description

The Prism 7 Git repository will not build in Visual Studio 2017.

### Steps to Reproduce

1. Clone Repository in Visual Studio 2017
2. Rebuild

### Expected Behavior

All projects should build without errors.

### Actual Behavior

Most of the projects fail to load.

The test projects fail with errors similar to the following:

**Severity	Code	Description	Project	File**
Error	NU1105	Unable to find project information for 'C:\Users\Robert\Source\Repos\Prism\Source\Prism\Prism.csproj'. The project file may be invalid or missing targets required for restore.	Prism.Tests	C:\Users\Robert\Source\Repos\Prism\Source\Prism.Tests\Prism.Tests.csproj	1	

### Basic Information

- Version with issue:  Latest commit 9399b9d  6 days ago
- Last known good version: Unknown
- Xamarin.Forms version: (Not in Use)
- IDE: Visual Studio 2017 Version 15.4.0

### Reproduction Link

https://github.com/PrismLibrary/Prism.git

### Remarks

Additional information here:
https://stackoverflow.com/q/54160689

I use Prism 6 extensively in my current work project, and I love it, but I also know that I don't fully utilize it, or understand the architecture well enough to make the migration to Prism 7.  The documentation is a big help, and I'd love to contribute to making the library better, but I don't understand it well enough to do that, and I don't know how to bridge that gulf.  I'm aware that this could be "closed as RTFM," but I couldn't find any documentation anywhere that would help me understand how your build system works well enough to fix the errors.

On a personal note, if I checked in a change that broke the build, I'd be buying donuts the next day. ;)

**Comment by brianlagunas** [comment] 2019-01-12 16:51
Duplicate of #1652

**Closed by brianlagunas** 2019-01-12 16:51 UTC

**Comment by robertwharvey** [comment] 2019-01-12 17:02
Thanks, Brian.
