### ISSUE TITLE
Crash on Xamarin.Android when using hardware back button

### ISSUE THREAD

**Issue by prahna** [PrismLibrary/Prism#1708] opened 2019-02-21 18:00 UTC
### Description
We have an app in Xamarin.Forms, and this issue happens sometimes when doing a simple back navigation when the app goes to sleep. 
### Steps to Reproduce
Unfortunately, I wasn't able to reproduce the bug 100% of the time, but these are the repro steps that I have :
1. Open app
2. Put app in background
3. While it's going in background, tap the back button

This is the error and the stack trace as gathered from AppCenter:
PageUtilities.GetCurrentPage (Xamarin.Forms.Page mainPage)
System.NullReferenceException: Object reference not set to an instance of an object

PageUtilities.GetCurrentPage (Xamarin.Forms.Page mainPage)
PrismApplicationBase.OnSleep ()
App.OnSleep ()
Application.SendSleep ()
FormsAppCompatActivity.OnStateChanged ()
FormsAppCompatActivity.OnStop ()
Activity.n_OnStop (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object.25(intptr,intptr)

After seeing the code in the GetCurrentPage method, I see that it tries to access the navigation stack from page, but maybe after app goes OnSleep, the navigation stack gets cleared ? so that would cause the NullReferenceException.

### Expected Behavior
The app shouldn't crash
### Actual Behavior
App crashes
### Basic Information

- Version with issue: XF 3.4.0 - PrismForms 7.0.0.396
- Last known good version: -
- Xamarin.Forms version: 3.4.0.1029999
- IDE: VS17 Enterprise

Thank you for the support !

**Comment by brianlagunas** [comment] 2019-02-22 19:36
Unfortintaely, this is going into the "no repro link privides" / "cannot reproduce". If you can actually get this to throw in your app, then please help us out and debug the issue and see if tou can fix it.  If you can, we would love to have the PR.

**Comment by andrybalko** [comment] 2019-09-10 10:16
I also experienced this issue. Exception was the same.
Steps were similar to ones mentioned initially with some remarks:
2 step - put app in background right after its launch
3. switch back to the app after a few seconds. 

To solve this I've added empty handlers to the App class without calling its base realization:
		```
protected override void OnResume()
		{
		}
		protected override void OnSleep()
		{
		}
```

**Comment by dansiegel** [comment] 2019-09-10 14:40
@andrybalko While I appreciate that you are experiencing the issue, you haven't provided a sample that reproduces the issue so we still wouldn't be able to look into this.

**Comment by andrybalko** [comment] 2019-09-10 15:42
[PrismCrash.zip](https://github.com/PrismLibrary/Prism/files/3596539/PrismCrash.zip)
simple project to reproduce this issue. I've reproduced in on Android device

**Comment by thisisthekap** [comment] 2019-10-01 14:08
@dansiegel As @andrybalko was able to provide a simple sample project to reproduce the issue, this bug may be reopened.

**Comment by dansiegel** [comment] 2019-10-01 14:12
to be verified

**Comment by AmrAlSayed0** [comment] 2019-11-06 09:46
I understood the problem now. The problem is not with the delay. The problem is with setting/navigating to the main page all together. If the MainPage is never set both these parametes are passed as null which causes an NRE.
In the OnSleep
https://github.com/PrismLibrary/Prism/blob/05972600e0baebbd4aa9733c809b3f2bcd39ec43/Source/Xamarin/Prism.Forms/PrismApplicationBase.cs#L239
and OnResume
https://github.com/PrismLibrary/Prism/blob/05972600e0baebbd4aa9733c809b3f2bcd39ec43/Source/Xamarin/Prism.Forms/PrismApplicationBase.cs#L233
This causes and NRE here
https://github.com/PrismLibrary/Prism/blob/05972600e0baebbd4aa9733c809b3f2bcd39ec43/Source/Xamarin/Prism.Forms/Common/PageUtilities.cs#L273
when the Navigation is accessed.
Project for reproduction.
[PrismCrash.zip](https://github.com/PrismLibrary/Prism/files/3813652/PrismCrash.zip)

**Comment by brianlagunas** [comment] 2019-11-07 15:28
Fixed via #1945

**Closed by brianlagunas** 2019-11-07 15:28 UTC
Labels: XF

**Comment by WilliamWatterson86** [comment] 2019-11-21 13:52
@brianlagunas - will there be a nuget release for this one?

**Comment by dansiegel** [comment] 2019-11-21 15:26
@WilliamWatterson86 we actually have a NuGet available on our CI feed as soon as the CI build finishes post PR merge...
