### ISSUE TITLE
PrismNavigationPage doesn't allow you to change navbar title color

### ISSUE THREAD

**Issue by sact1909** [PrismLibrary/Prism#3134] opened 2024-05-09 05:56 UTC
### Description

in your documentation you said, PrismNavigationPage will be registered as the default navigation page in case we don't have a custom navigation page, but also you mention this 

My current version (but it happen with any version not matter what)
.NET MAUI 8
Prism.DryIoC.Maui = 9.0.401-pre

![image](https://github.com/PrismLibrary/Prism/assets/23615129/4015bb7a-a0d1-4630-9482-bf69aef9583d)

that's why I would like to keep the PrismNavigationPage as default, but this doesn't allow you to change the navbar title color, no matter what you do, it will be black

this is how my PrismStartup,cs looks
![image](https://github.com/PrismLibrary/Prism/assets/23615129/5da224a5-8c7d-4eb4-9aae-a54729a7c6a7)

this is how my Resources/Styles/Styles.xml looks (I'm forcing the bartextcolor to be red in any scenario)
![image](https://github.com/PrismLibrary/Prism/assets/23615129/faf8c3f6-77ba-4dcc-91c0-b7b260efcb77)

and it still black
![image](https://github.com/PrismLibrary/Prism/assets/23615129/b3d7d961-00f7-4ee0-8c46-6ec809523ba7)

Please download the Sample Project (is the same that I use for the images)
[PrismNavigationPageBug.zip](https://github.com/PrismLibrary/Prism/files/15258118/PrismNavigationPageBug.zip)

### Steps to Reproduce

1. Create a New Project using the Prism Template  Projects
2. Go to  Resources/Styles/Styles.xml
3. Search for the style section with TargetType=NavigationPage
4. Set the BarTextColor property  to whatever color, in my case I use Red
5. Run the Project (and the bartextcolor in the navbar will be still in color black)

### Platform with bug

.NET MAUI

### Affected platforms

Android

### Did you find any workaround?

Obvious If register the NavigationPage in the PrismStartup.cs it will work, 
![image](https://github.com/PrismLibrary/Prism/assets/23615129/9e66a641-bd11-46d4-a7c9-4310b22ef558)

but it is supposed to be there when you don't have any other custom NavigationPage, that what you say

**Comment by AmrAlSayed0** [comment] 2024-05-11 07:43
Add [Style.ApplyToDerivedTypes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.style.applytoderivedtypes) to your `NavigationPage` style or just target the `PrismNavigationPage` directly. I think that will solve your issue.

Also this is not specific to Prism. Any derived types will not have the styles applied without [Style.ApplyToDerivedTypes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.style.applytoderivedtypes).

**Comment by sact1909** [comment] 2024-05-11 10:26
> Add [Style.ApplyToDerivedTypes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.style.applytoderivedtypes) to your `NavigationPage` style or just target the `PrismNavigationPage` directly. I think that will solve your issue.
> 
> Also this is not specific to Prism. Any derived types will not have the styles applied without [Style.ApplyToDerivedTypes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.style.applytoderivedtypes).

I never thought it was a prism problem, but is something that happens with a prism class, I think that there could exist a Prism solution for this, setting that property as default anywhere

but glad to see that property, never seen it before, really appreciate that info, it helped me a lot

note:
I tried to target the PrismNavigationPage directly but that doesn't work, maybe this could be another workaround for Prism if the allow to target the PrismNavigationPage 


Thanks for the help

**Comment by dansiegel** [comment] 2024-05-24 01:14
closing this as the issue is due to the fact that your style is explicitly on a NavigationPage and could be fixed by:
1) applying it to PrismNavigationPage
2) applying it to derived types `ApplyToDerivedTypes="True"`

**Closed by dansiegel** 2024-05-24 01:14 UTC
Labels: bug, to verify
