### ISSUE TITLE
[BUG]  Back Button Navigation from child ContentPage closing page

### ISSUE THREAD

**Issue by MardorZ** [PrismLibrary/Prism#2843] opened 2023-03-17 10:43 UTC
### Description

When navigating from the MainPage to a DetailPage and then pressing the hardware back button of my android 11 device the app does navigate back to the MainPage but proceedes to go back a second time, which closes the app.

It seems that the GoBack Navigation is handled multiple times.

I am using the following nuget packages:

> <ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="5.0.0" />
		<PackageReference Include="Prism.DryIoc.Maui" Version="8.1.273-pre" />
		<PackageReference Include="ReactiveUI.Fody" Version="18.4.26" />
		<PackageReference Include="Shiny.Framework" Version="3.0.0-alpha-0058" />
		<PackageReference Include="Shiny.Extensions.Configuration" Version="3.0.0-alpha-0533" />

### Steps to Reproduce

1. Create a NET MAUI app with prism and/ or shiny framework.
2. Add a second ContentPage to the app
3. Add a button to the MainPage which navigates to the second ContentPage
`await _navigationService.NavigateAsync("DetailPage");`
4. Launch the App
5. Click the button which navigates to the second ContentPage and then press the hardware back button (or swipe when gestures are enabled) to go back.

Expected: The app navigates back to the main page.
Actual: The app briefly navigates back to the main page but navigates back a second time which closes the app.

### Platform with bug

.NET MAUI

### Affected platforms

Android

### Did you find any workaround?

I fiddled with many overrides of the various OnBackPressed Events but had no luck. For now we are waiting for a fix...

### Reproduction app

https://github.com/MardorZ/BackButtonNavigationBug

**Comment by brianlagunas** [comment] 2023-03-17 14:27
Please provide the required reproduction app or this issue will be closed.

**Comment by MardorZ** [comment] 2023-03-19 10:12
> Please provide the required reproduction app or this issue will be closed.

https://github.com/MardorZ/BackButtonNavigationBug

**Comment by dansiegel** [comment] 2023-03-21 23:44
This appears to be a duplicate of #2815. Please follow that issue for more information. If you feel this is a similar but different issue please feel free to let me know.

**Closed by dansiegel** 2023-03-21 23:44 UTC
Labels: bug, duplicate
