### ISSUE TITLE
[Bug] RegisterForNavigation doesn't make models singleton, doesn't work properly with Android background host

### ISSUE THREAD

**Issue by petermillsacumentive** [PrismLibrary/Prism#1884] opened 2019-08-21 12:40 UTC
### Description

When using **RegisterForNavigation** to link a model and a page, this doesn't seem to be using a singleton. Pages are not disposed of when the UI is closed. This causes a problem where a background host is used and the UI is closed and re-loaded (you end up with two copies of the ViewModel in play, firing their events multiple times, timers, etc). 

### Steps to Reproduce

1. Code a background service in Android with a basic UI
2. User opens UI up, which starts the background service automatically
3. User closes the UI by swiping
5. UI is re-opened by pressing on an intent or from the main menu
6. UI re-appears

### Expected Behavior
Model from before is used or the old one disposed of as some point by the GC

### Actual Behavior
Events and timers are firing in the view model which can no longer be accessed, as well as the new one. Each time UI is closed & re-opened the models keep growing.

### Basic Information

- Version with issue: 7.1.0.431
- Last known good version: N/A
- Xamarin.Forms version: 3.6.0.539721
- IDE: Visual Studio 2019 16.0.6

### Reproduction Link

Might be possible, however should be possible to demonstrate with any background service style implementation.

**Comment by umitnuri** [comment] 2019-08-21 12:52
I believe Brain is going to ask you the re-production code. Be prepared just saying...

**Comment by brianlagunas** [comment] 2019-08-21 15:06
Closing as no reproduction app provided.

**Closed by brianlagunas** 2019-08-21 15:06 UTC

**Comment by brianlagunas** [comment] 2019-08-21 15:08
Just read this, and VM's are not registered as singletons. That's very bad practice. you are responsible for managing your app state. This is not a bug.

**Comment by petermillsacumentive** [comment] 2019-08-21 15:17
I shall work on an app to reproduce the problem. 

I think to say a singleton in this instance is bad practice (I assume you mean in all cases too) is a bit of a sweeping statement. The UI on the App I'm supporting is very simple and the focus is the background thread that is doing a lot of BLE reading. 

As it stands with the implementation with Prism means I have events I need to make sure I tear down by hand, because the VM lives forever and I get n-number of them fire each time the UI is closed. e.g. I have an event firing (Subscribe using Prism) to alert the user they have turned their Bluetooth off. I need a singleton because I can't have the thing firing 4 times because the user closed the UI 4 times. Also I've got some state I don't want to be thrown away (but I don't want to put it in SQLite either).

For the moment I've had to stop using RegisterForNavigation and go with a custom implementation. For the moment I'm leaving the rest of Prism in.

**Comment by brianlagunas** [comment] 2019-08-21 15:22
No need for a repo. This is not something Prism will support. A singleton VM in general is bad practice and I would never recommend it. Your services can be singletons. However, you do what you need to do in order to make your app work.
