### ISSUE TITLE
NavigationService might be null (System.NullReferenceException was thrown)

### ISSUE THREAD

**Issue by SunboX** [PrismLibrary/Prism#1119] opened 2017-07-18 09:26 UTC
I can't tell you exactly when this happens. But it seems that the NavigationService was not instantiated when the app got suspended. Imagine, the app was started in a share pane view and closes itself as soon as it recieved all data.

![image](https://user-images.githubusercontent.com/83344/28310124-ac39051a-6bab-11e7-9f1d-7febc8f47976.png)

**Comment by SunboX** [comment] 2017-07-18 09:30
...same for `SessionStateService`

![image](https://user-images.githubusercontent.com/83344/28310323-6e0899ee-6bac-11e7-8f8e-0dafd50ecff1.png)

**Comment by SunboX** [comment] 2017-07-18 09:32
This will fix the issue:

```c#
/// <summary>
/// Invoked when application execution is being suspended. Application state is saved
/// without knowing whether the application will be terminated or resumed with the contents
/// of memory still intact.
/// </summary>
/// <param name="sender">The source of the suspend request.</param>
/// <param name="e">Details about the suspend request.</param>
private async void OnSuspending(object sender, SuspendingEventArgs e)
{
    IsSuspending = true;
    try
    {
        var deferral = e.SuspendingOperation.GetDeferral();

        //Custom calls before suspending.
        await OnSuspendingApplicationAsync();

        //Bootstrap inform navigation service that app is suspending.
        NavigationService?.Suspending();

        // Save application state
        var saveAsync = SessionStateService?.SaveAsync();
        if (saveAsync != null)
        {
            await saveAsync;
        }

        deferral.Complete();
    }
    finally
    {
        IsSuspending = false;
    }
}
```

**Comment by bartlannoeye** [comment] 2017-07-19 06:43
Thanks for reporting.

As mentioned in #1121, the fix is hiding the real issue (not having an initialized NavigationService). We're redoing part of the application initialization (planned for 1st week of August), so the initial problem will be tackled there.

**Comment by SunboX** [comment] 2017-07-19 06:59
Hey, no problem. I just needed a solution for my application crash. You are right, the root cause should be resolved, not the effect. 😄 

Thanks for your work! 👍

**Comment by artemious7** [comment] 2017-08-28 08:19
You told it was planned for 1st week of August. Last days of August - still nothing fixed? :-(

**Comment by brianlagunas** [comment] 2017-08-28 13:54
@artemious7 there is a workaround in this thread, so you should not be blocked.  Also, we accept PR's from the community, so if you wanted to fix it you can.

**Comment by rainman-63** [comment] 2018-04-26 16:31
The root cause we've experienced is when the UWP app uses App2App Communication Services and the UWP app has previously been suspended or closed.  When the next App2App communication comes in, the UWP app is activated via OnBackgroundActivated, thus the Prism InitializeShell and InitializeFrameAsync methods are not executed, so NavigationService and SessionStateService are null.

**Comment by brianlagunas** [comment] 2018-04-26 19:33
Actually, we are hoping this is solved with the upcoming Template10/Prism merge.

**Comment by mfe-** [comment] 2018-06-25 12:37
@brianlagunas Whats the state of the Template10/Prism merge? Is it somewhere tracked?

**Comment by bartlannoeye** [comment] 2018-06-25 12:39
Brian is currently occupied with family matters. I'll check with Jerry and come back to this when we have an answer.

**Comment by sebfrie** [comment] 2018-07-14 13:40
Any news or even timeline to share?

**Comment by bartlannoeye** [comment] 2018-07-14 18:06
Jerry was on vacation, he should be back one of these days so I'm trying to get a status update asap.

**Comment by bartlannoeye** [comment] 2018-07-20 15:00
Got new from Jerry, he's just back out of vacation and is wrapping up some other articles first. The current state of his work can be found in the [Template 10 repo](https://github.com/Windows-XAML/Template10/tree/master/Source). I'm leaving on vacation this weekend and plan to test the upgrade path from v6 to the new code base (and proof test it in a real LoB application) once I'm back and hope to land on something by the end of summer.

**Comment by brianlagunas** [comment] 2018-09-26 01:03
Template10 merged complete. This should no longer be an issue.

**Closed by brianlagunas** 2018-09-26 01:03 UTC
Labels: UWP
