### ISSUE TITLE
NavigationParameters with URL as a Parameter

### ISSUE THREAD

**Issue by JamesPetras** [PrismLibrary/Prism#748] opened 2016-08-28 21:22 UTC
HI Guys,

I think the navigation service doesn't work (doesn't find the model) when one of the parameters has a URL inside 
```

NavigationParameters param = new NavigationParameters();
			param.Add("URL", "http://google.com");
			param.Add("Title", "Go premium");

			await _navigationService.NavigateAsync(PageCodes.NavigateTo_WebPage, param);
```
This doesn't get into the OnNavigatedTo(NavigationParameters parameters) method of my NavigateTo_WebPage page. As soon as I removed the http://.... and replaced with Test it worked.

Am I missing something obvious or this is an actual bug?

**Comment by brianlagunas** [comment] 2016-08-29 14:37
I am unable to reproduce this issue.  I wrote two unit tests and even ran a sample app and was not able to duplicate.  Do you have a sample that can demonstrate this issue?

**Comment by brianlagunas** [comment] 2016-08-29 21:42
I'm closing this as I could not verify it.  If you can provide a sample I will take a look.

**Closed by brianlagunas** 2016-08-29 21:42 UTC

**Comment by JamesPetras** [comment] 2016-08-30 08:24
You are right. It is working. 

I didn't setup ViewModel correctly 

Sorry for the false alarm

Cheers
