### ISSUE TITLE
Do Prism UWP and Xamarin Forms UWP Play Well Together?

### ISSUE THREAD

**Issue by adamhill** [PrismLibrary/Prism#552] opened 2016-04-24 20:39 UTC
Should Prism and Xamarin Forms UWP play well together? 

I  have tried taking the UsingDependencyService example, adding a UWP project, adding Nuget references to match packages.config in Droid and iOS to project.json, then following James Montemagno's directions -[here]( https://blog.xamarin.com/getting-started-with-xamarin-forms-windows-10-preview )

The build errors I am getting are:

```
Cannot resolve Assembly or Windows Metadata file 'Prism.Unity.Forms.dll' UsingDependencyService.UWP	C:\Dev\GitHub\xamarin\Prism-Samples-Forms\UsingDependencyService\UsingDependencyService\UsingDependencyService.UWP\UsingDependencyService.UWP.csproj  Build

Type universe cannot resolve assembly: Prism.Unity.Forms, Version=6.2.0.0, Culture=neutral, PublicKeyToken=null.	UsingDependencyService.UWP	C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.2\Microsoft.Windows.UI.Xaml.Common.targets	352	Build	
```

If I add any version of  'Prism.Unity.Forms' to the UWP project I get a complaint that it cant find PrismApplicationBase in the newly added Prism.Unity.Forms.

Any ideas?

Here are packages.config and project.json.

packages.config
------------
```
<packages>
  <package id="CommonServiceLocator" version="1.3" targetFramework="xamarinios10" />
  <package id="Prism.Core" version="6.1.0" targetFramework="xamarinios1" />
  <package id="Prism.Forms" version="6.1.0-pre1" targetFramework="xamarinios10" />
  <package id="Prism.Unity" version="6.2.0-pre1" targetFramework="xamarinios10" />
  <package id="Unity" version="4.0.1" targetFramework="xamarinios1" />
  <package id="Xamarin.Forms" version="2.0.0.6490" targetFramework="xamarinios10" />
</packages>
```

project.json
-----------
```
dependencies": {
    "CommonServiceLocator": "1.3.0",
    "Microsoft.ApplicationInsights": "1.0.0",
    "Microsoft.ApplicationInsights.PersistenceChannel": "1.0.0",
    "Microsoft.ApplicationInsights.WindowsApps": "1.0.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0",
    "Prism.Core": "6.1.0",
    "Prism.Forms": "6.1.0-pre1",
    "Prism.Unity": "6.2.0-pre1",
    "Unity": "4.0.1",
    "Xamarin.Forms": "2.0.0.6490"
}"
```

**Comment by bartlannoeye** [comment] 2016-04-25 05:35
Duplicate of #466, this is a manual fix for now and will be fixed in the packages on the next release (after Xamarin Evolve)

**Closed by bartlannoeye** 2016-04-25 05:35 UTC

**Comment by adamhill** [comment] 2016-04-25 14:20
So the manual fix is to use 'Prism.Unity.Forms' instead of 'Prism.Forms' or in addition to?

Will the shown version of 6.1.x work or do I need to use the Latest 6.2.x-pre3 or -pre4 if available?
