### ISSUE TITLE
[Bug] Navigation not working after upgrading to 8.0

### ISSUE THREAD

**Issue by dzebas** [PrismLibrary/Prism#2295] opened 2021-01-05 01:14 UTC
**Description**

Xamarin Forms with TabbedPage navigation is not working after upgrading Prism to 8.0.
Please note that AutowireViewModel is set to true on all pages, so this is not the issue.

**Steps to Reproduce**

Run sample project, click on 'TO CONTENT PAGE1_1" button, it navigates to page 1.
Now update Prism to 8.0, repeat same step, nothing happens.

**Expected Behaviour**

Should navigate to page 1.

**Actual Behaviour**

Does not navigate to page 1 with Prism 8.0

**Basic Information**

- Version with issue: 8.0.0.1909
- Last known good version: 7.2
- Xamarin.Forms version: 4.8
- IDE: Visual Studio 2019

**Screenshots**

None

**Reproduction Link**

https://github.com/uwe-e/PrismPages

**Comment by brianlagunas** [comment] 2021-01-05 16:23
Closing as a duplicate of #2218

**Closed by brianlagunas** 2021-01-05 16:23 UTC
Labels: bug, to verify
