### ISSUE TITLE
Issue with loading modules from path, with valid special symbols in file path like #

### ISSUE THREAD

**Issue by Diaver** [PrismLibrary/Prism#926] opened 2017-01-31 05:40 UTC
Prism doesn't want to load modules on demand when there are some valid special symbols in file path like **#**.
The main issue in method: **`class AssemblyResolver:  private static Uri GetFileUri(string filePath)`** 
It use: **`Uri.TryCreate(filePath, UriKind.Absolute, out uri)`** for extracting file path from path identifier like **`file:///D:/Prism/Prism-Samples-Wpf-master`** and return Uri with LocalPath property.
But there is a problem with method **Uri.TryCreate**. It split path by special symbols like #
From:
`file:///D:/C#/Prism/Prism-Samples-Wpf/Modularity/ModularityWithUnity/ModularityWithUnity.Desktop/bin/Debug/Modules/ModularityWithUnity.Desktop.ModuleB.dll`
To:
`D:\C`

### Package info

- Platform: WPF, Windows
- Prism version: 6.2.0, 6.1.1

### Repro steps

Download and extract example https://github.com/PrismLibrary/Prism-Samples-Wpf/tree/master/Modularity to folder with # symbol and run

**Comment by dvorn** [comment] 2017-01-31 10:55
@Diaver Try #928.

**Comment by dvorn** [comment] 2017-01-31 11:34
If I understand it correctly, the problem is the following.

Uri constructors (and TryCreate) that takes a string argument works as follows: if the string starts with "file://", then the file name is assumed to be already escaped.  If not, the file name is assumed not been escaped yet.

However, Assembly.CodeBase returns a string which starts with file:/// but is not escaped.

Need to use Assembly.EscapedCodeBase instead.

**Comment by andreax64** [comment] 2017-01-31 18:13
I have the same problem with the same platform at the same point with Prism.WPF 6.2.0.
The debugger screenshot:
![exception](https://cloud.githubusercontent.com/assets/25463355/22478184/ec4726ba-e7b6-11e6-92e7-e5bef8eb2374.png)

**Comment by brianlagunas** [comment] 2017-01-31 18:15
@andreax64 of course, this has not been fixed in 6.2 because it has just now been reported.  @dvorn asked if you could try PR #928 to see if it fixes your issue.

**Comment by Diaver** [comment] 2017-02-01 01:21
@brianlagunas @dvorn @andreax64 
#928 fixed this issue!

**Comment by brianlagunas** [comment] 2017-02-01 01:23
Great.  Thanks for letting us know. As soon as @dvorn adds a test or two then I'll get it merged.

**Comment by dvorn** [comment] 2017-02-02 18:18
Some explanations.

ModuleInfo.Ref property is set in two places: by the ConfigurationModuleCatalog class (https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Modularity/ConfigurationModuleCatalog.Desktop.cs#L75) and by the DirectoryModuleCatalog class (https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Modularity/DirectoryModuleCatalog.Desktop.cs#L240).

The Ref property contains the URI of the module assembly file as a string.

It is then used by the FileModuleTypeLoader class with passes the uri string unmodified to AssemblyResolver.LoadAssemblyResolver(string) method.

The LoadAssemblyResolver creates an Uri from the string.  Thus, the Ref should be a valid uri string.  In particular, properly escaped.

Both ConfigurationModuleCatalog and DirectoryModuleCatalog classes create the uri string which starts with "file://".  However, DirectoryModuleCatalog does that by creating an Uri and then taking its string representation (https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Modularity/ConfigurationModuleCatalog.Desktop.cs#L44).  This uri string will always be properly escaped.  But the DirectoryModuleCatalog does that by just taking type.Assembly.CodeBase.  This looks like an uri string (it starts with "file://"), but it is not properly escaped (if needed).  Thus, it does not work when there are special characters in the full path.  

The remedy, as suggested by Microsoft (https://connect.microsoft.com/VisualStudio/feedback/details/750678/codebase-does-not-correctly-escape-character), is to use Assembly.EscapedCodeBase.

Another related issue is that before FileModuleTypeLoader passes the uri string to AssemblyResolver, it attempts to determine the file size for progress reporting (https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Modularity/FileModuleTypeLoader.Desktop.cs#L119).  It need access to the same file as AssemblyResolver and it should have used the same approach as AssemblyResolver, but it uses a simplified approach instead: it simply trims the "file://" prefix from the uri string.  This will not work if the uri string is really escaped.

That was fixed in the PR too.

**Comment by brianlagunas** [comment] 2017-02-03 18:27
Fixed by @dvorn PR

**Closed by brianlagunas** 2017-02-03 18:27 UTC
Labels: WPF
