### ISSUE TITLE
add a replace page method for INavigationService (Xamarin Form)

### ISSUE THREAD

**Issue by guidebee** [PrismLibrary/Prism#990] opened 2017-03-16 13:25 UTC
Currently the INavigationService for Xamarin From has GoBack(Pop) and Navigate (Push) of pages, from time to time for some apps , I just want to keep the current navigation stack and only want to replace the the page on top of the stack with new page .

Is it possible to provide a new method to replace top page with new one ?

Tried to Combine GoBack(pop) and then Navigate(push) to implement above behavior doesn't seems work properly.

**Comment by nuitsjp** [comment] 2017-03-16 13:51
This Issue #989 will be helpful. 
Prism can reset the navigation stack by doing the following.

```cs
navigationService.NavigateAsync("/FooPage");
```
Please start navigation name with slash.

**Comment by guidebee** [comment] 2017-03-16 14:04
Thanks, this is not I wanted, I don't want to reset the whole stack, just want to replace the top page on the stack, everything underneath will remain.

**Comment by brianlagunas** [comment] 2017-03-16 14:14
This is a duplicate of #921, so I am closing it.  You should follow #921 for updates on this feature.  So I can understand your scenario, can you provide more information about the structure of your navigation stack?  Is it a modal stack or are you within a NavigationPage?  Can you provide what you nav stack looks like?

**Closed by brianlagunas** 2017-03-16 14:14 UTC
