### ISSUE TITLE
[Enhancement] Regions in PRISM for Xamarin.Forms 

### ISSUE THREAD

**Issue by juanperezADD** [PrismLibrary/Prism#1072] opened 2017-06-01 11:07 UTC
We are a company that has been using PRISM in multiple WPF projects for many years.

Now, we want to develop a new multiplatform application for mobile, tablet, desktop, etc. Following the TODO app (https://github.com/brianlagunas/TodoApp), we have started by creating a solution for each device. For example, the desktop solution is created with WPF and the mobile solution with Xamarin.Forms. We can reuse most of the code by sharing the view models which are .Net Standard libraries that use PRISM.Core.

However, Microsoft recently announced that Xamarin.Forms will support WPF in addition to Linux and MacOS.

Before this, we understood that Xamarin.Forms was only for mobile applications. However, after this announcement, Xamarin.Forms will also start to be used as a framework for desktop applications.

That is the reason why we are thinking to work with Xamarin.Forms as a main development framework for all our applications, both for mobile and desktop devices. We could have different solutions for each device, but all of them would work with Xamarin.Forms with all the advantages that it represents (only one xaml to learn, only one framework, etc.).

The problem is that PRISM for Xamarin.Forms does not have the concept of region. For us, in tablet or desktop solutions, this feature is essential to be able to create modular applications.

In this post (http://brianlagunas.com/first-look-at-the-prism-for-xamarin-forms-preview/#comment-17787), Brian explained that regions didn't make sense in Xamarin.Forms for mobile devices. But now, after this announcement, it makes sense for larger devices like a tablet or desktop. For example, there is a framework called Exrin (https://xamarinhelp.com/container-region-stack-navigation-exrin/) that already supports regions in Xamarin.Forms.

Is there any plan to include the concept of regions in PRISM for Xamarin.Forms? We think that both the community and us will be very interested.

**Comment by brianlagunas** [comment] 2017-06-02 20:54
I'm not 100% sold yet, but I'll let the community weigh in.

**Comment by dansiegel** [comment] 2017-06-05 21:32
@juanperezADD I suppose this could maybe make sense for the yet to arrive CarouselView, but I'm not sure how this would make sense to implement for Xamarin Forms at current. 

Pointing to the fact that Xamarin Forms is "supporting WPF" doesn't change how Xamarin Forms is implemented or how it works. Before a discussion could really begin on should we support regions, I think it's important to define how (using the Xamarin Forms API) it would even work and be implemented.

**Comment by juanperezADD** [comment] 2017-06-06 16:24
Both, @brianlagunas and @dansiegel, talk about that if the regions were added, it would be a completely different API that what exists in WPF now. But, What limitations does XF because of it's nature? Are they possible to solve?

**Comment by juanperezADD** [comment] 2017-06-06 16:38
@dansiegel We think regions are definitely needed for larger devices like a tablet or desktop, maybe even for phones when using MasterDetailPage or TabbedPage for navigation. Regions allow us to compose a view with smaller views and it has it's own region navigation service.

**Comment by brianlagunas** [comment] 2017-06-06 16:43
To do regions properly is not a simple task and will require a ton of planning as well as feature scope.  For example, do you expect regions to have their own navigation stack with GoForward and GoBack methods, manage object lifetimes, manage active states, support nested regions, custom region behaviors, customer region adapters, interact with the hardware/software back buttons just to name a few.  Regions aren't as simple as show something in the area.  A lot of thought needs to go into them and a ton of code will be added to Prism in order to support them.  Also, the API will not match the WPF version for a number of reasons.  We also have to consider native UWP in this feature.

**Comment by dansiegel** [comment] 2017-06-06 16:50
@juanperezADD changing the target platform from Phone to Desktop doesn't change the API or how Xamarin Forms works. As @brianlagunas mentioned it requires a lot of planning and more than simply saying you want Regions, you need to define how it will would work within the given API. Also if we were to share the interface between UWP & Xamarin Forms then it would need to be done in a way that makes sense for both API's.

**Comment by Suriman** [comment] 2017-06-06 17:10
As I understand it, the problem is technical, or rather time and development effort to implement a suitable solution.

Regardless of this, what seems pretty obvious is that if XF is used in a future desktop option it will have to adapt to features that other frameworks like WPF, that were originally born on desktop, have.

Let's take another example, the development companies of controls should also include controls that are originally designed for desktop in their versions for XF, for example, the Ribbon.

As I see it, the future should have a single framework to develop for phone, tablet and desktop, and this framework should be XF. Both XF and PRISM as well as third party control companies will have to adapt to this new scenario if we really want to see the fulfillment of a single way of doing things.

**Comment by brianlagunas** [comment] 2017-06-06 17:22
The problem with writing a single API that works across multiple platforms is you MUST develop against the least common denominator.  Not all controls that are WPF controls can exist in an XF app.  They will have to be completely rewritten to fit the target platforms, which will be the least common set of functionality across all platforms.

You are over simplifying a broad concept.  The devil is in the details.  I will also boldly say that I would never write an app meant for WPF in XF.  That would be ridiculous.  If you have a simple mobile app that you want to port to WPF, sure why not.

Keep in mind that XF has tons of issues with Android, iOS, and UWP as it is.  It's a real massive pain in the ass.  Now add another platform on top of that and it's cluster fuck of problems.  I really wish Xamarin would concentrate on stabilizing what they have now before trying to shove another platform into an unstable code base.  Wow, I went way off topic there :)

**Comment by juanperezADD** [comment] 2018-01-19 09:37
@brianlagunas In December this issue was added as a "TO DO" in the Kanban board. Are there any plans to implement it this year? This is a feature that we are looking forward to get since XF supports WPF.

**Comment by brianlagunas** [comment] 2018-01-19 15:17
@juanperezADD This is not planned for implementation anytime soon.  XF "sort of" supports WPF, so I would be careful placing all you eggs in that basket.

**Comment by dazinator** [comment] 2018-02-13 12:23
> Keep in mind that XF has tons of issues with Android, iOS, and UWP as it is. It's a real massive pain in the ass. Now add another platform on top of that and it's cluster fuck of problems. I really wish Xamarin would concentrate on stabilizing what they have now before trying to shove another platform into an unstable code base. 

100% this :-)
Combine that with the general tooling instabilities that we are living through in the form of VS 2017, net.core, netstandard, msbuild sdk changes and it's amazing that any of us are managing to remain productive at all!

**Comment by urodolf** [comment] 2019-07-19 07:15
I have seen that this issue has been included to resolve in version 7.3.
Do you know when this release is planned?
We are very interested in this funcionality.

**Comment by dansiegel** [comment] 2019-07-19 13:20
@urodolf well 7.2 was theoretically considered stable last week... now that I'm getting back I can actually address that it didn't deploy to NuGet... once that hits NuGet we'll be looking ahead to issues we want to address for 7.3

**Comment by mackayn** [comment] 2019-07-22 09:55
Would have been awesome if it made it into 7.2 as it's something we're having to work round UX design wise but it will be great to see this added to Prism.

**Comment by Suriman** [comment] 2019-11-13 09:51
Please do not close this issue! 

The need is still fully active in our company. We use PRISM in WPF and we want to migrate to Xamarin Forms to generate the UI on Desktop and Web (now that there are renders for WebAssembly of UNO Platform). Regions may not make much sense for mobile, but they make all the sense in the world on desktop and in a web application and we want to use only one framework (XF) to generate the entire user interface for any platform (desktop, mobile and Web).

**Comment by urodolf** [comment] 2019-11-13 10:08
Our company has the same needs, we want use XF to generate the entire interface for any platform (desktop, mobile and Web).

**Comment by brianlagunas** [comment] 2019-11-13 14:36
@Suriman and @urodolf If your companies need this feature so bad, how about you suggest to them to support Prism by sponsoring Dan and myself?

Sponsor Brian: https://github.com/sponsors/brianlagunas
Sponsor Dan: https://github.com/sponsors/dansiegel

**Comment by ChaseFlorell** [comment] 2019-11-13 17:57
@Suriman & @urodolf I know for a fact that Brian and Dan also accept pull requests. Heck, they took my xaml navigation stuff last year. This is an open source project and the maintainers have real / paying jobs that take priority. They're also really awesome to work with and will give guidance where they can as you submit your Pull Request(s).

**Comment by dansiegel** [comment] 2020-08-20 18:26
This feature is now available via #2077 the CI Build for Prism 8.0.0.1809 should be available in the next 20 minutes

**Closed by dansiegel** 2020-08-20 18:26 UTC
Labels: XF, enhancement, roadmap
