### ISSUE TITLE
Documentation for Prism 7?

### ISSUE THREAD

**Issue by avishnyakov** [PrismLibrary/Prism#1712] opened 2019-02-24 07:06 UTC
Hi team, 

It is challenging to find documentation on Prism 7. 
Any plans on improving this?

**Comment by bartlannoeye** [comment] 2019-02-24 08:31
Duplicate of #1632, #1648 and https://github.com/PrismLibrary/Prism-Documentation/issues/28

**Closed by bartlannoeye** 2019-02-24 08:31 UTC
