### ISSUE TITLE
ListDictionary TKey and TValue same type

### ISSUE THREAD

**Issue by DP7891** [PrismLibrary/Prism#1261] opened 2017-11-15 12:57 UTC
### Package info

- Platform: Windows
- Prism.WPF version: 6.3.0

### Repro steps

with the same "key" and "value" type you cannot use the Remove( TKey ) or Remove( TValue ) method

**Comment by DP7891** [comment] 2017-11-15 13:00
this is my fix
![grafik](https://user-images.githubusercontent.com/33690602/32837316-5ef556bc-ca0d-11e7-917b-b8ae5b4ba5fd.png)

**Comment by brianlagunas** [comment] 2017-11-15 15:03
Could you provide more detail?  I have no idea what you are talking about or what you are trying to do.

**Comment by dvorn** [comment] 2017-11-15 15:53
This is about the Prism.Common.Listdictionary class in Prism.Wpf.  When TKey and TValue is the same type, the methods Remove(TKey key) and Remove(TValue value) in ListDictionary<TKey, TValue> become ambiguous.

**Comment by brianlagunas** [comment] 2017-11-15 15:58
This is not a collection meant to be used generically.  These methods also work as intended for it's uses within Prism.

**Comment by brianlagunas** [comment] 2017-11-15 16:02
Also, I think you misunderstand what those methods are doing.  When you use the (key, value) method, you are removing values from the list with the given key, not actually removing the list.

This is described in the method comments:
```
 /// <summary>
        /// Removes a value from the list with the given key.
        /// </summary>
        /// <param name="key">The key of the list where the value exists.</param>
        /// <param name="value">The value to remove.</param>
```
What you did was create an Extension method that actually removed the list from the collection, which is not the intended function of the method you are using.

**Comment by dvorn** [comment] 2017-11-15 17:23
> This is not a collection meant to be used generically. 

Then we should make it internal.

**Comment by brianlagunas** [comment] 2017-11-15 17:32
Once you make something public for nearly 10 years, you can't just make it internal.  Also, the collection is working exactly as it should.  The OP did not understand what those methods actually did.

**Comment by dvorn** [comment] 2017-11-15 18:07
> These methods also work as intended for its uses within Prism.

> Also, the collection is working exactly as it should. 

The API of Listdictionary class is poorly designed.  Listdictionary<string, string> works in Prism.Modularity.ModuleDependencySolver only because it never attempts to remove neither key nor value.

**Comment by brianlagunas** [comment] 2017-11-15 18:11
Possibly, but this really is a non-issue.

**Comment by dvorn** [comment] 2017-11-15 18:25
Sure, not a big deal.  But the library provides _public_ general-purpose collection class, it does not behave well, and the users complain.

This can be fixed without breaking backward compatibility by adding RemoveKey(TKey) and RemoveValue(TValue) methods which will do exactly what Remove(TKey) and Remove(TValue) do.

**Comment by brianlagunas** [comment] 2017-11-15 18:28
The methods in the current API work as expected.  The remove Key/Value will first get the collection based on key, the loop through that collection and remove the value from that collection.

I am confused on what needs to change.

**Comment by dvorn** [comment] 2017-11-15 18:35
After the line https://github.com/PrismLibrary/Prism/blob/master/Source/Wpf/Prism.Wpf/Modularity/ModuleDependencySolver.cs#L59 add the line

`dependencyMatrix.Remove(module);`

and try compile.

**Comment by brianlagunas** [comment] 2017-11-15 18:37
So your main complaint is that the method Remove(value) doesn't accurately represent what the method does.  Instead RemoveValueFromLists(value) would make more sense?

**Comment by dvorn** [comment] 2017-11-15 18:42
Did you tried to compile?

**Comment by brianlagunas** [comment] 2017-11-15 18:43
No, I am working on other, more important things :)

**Comment by dvorn** [comment] 2017-11-15 18:45
The problem is not the meaningful name.  It does not compile.  Does not work at all.

**Comment by brianlagunas** [comment] 2017-11-15 18:51
Ahh, now I see what you mean. It is because of the method name :)

Should be named RemoveValue instead.  Actually looks like the easy fix is for both of the methods to be called RemoveValue.

**Comment by dvorn** [comment] 2017-11-15 19:00
No, method names should be different.  The problem is that there exist two methods with the same name (Remove) which differ only in argument type (TKey/TValue).  This becomes ambiguous when TKey and TValue are the same type.

**Comment by brianlagunas** [comment] 2017-11-15 19:01
Yeah that's what I meant.

`RemoveValue(TKey, TValue)` and `RemoveValue(TValue)`

That would fix the issue.

**Comment by dvorn** [comment] 2017-11-15 19:05
But this will be a breaking change.  Easy to fix though.

**Comment by brianlagunas** [comment] 2017-11-15 19:07
The good news is I don't think many people are using this anyways.  In 10 years this is the first I have heard of anyone using it. It will be noted as a break, and it will result in a build error so anyone using it will know where the break is.  If it was a behavior break, those are nearly impossible to find and I try to avoid those at all costs.

**Comment by brianlagunas** [comment] 2017-11-15 20:46
Fixed

**Closed by brianlagunas** 2017-11-15 20:46 UTC
Labels: bug, WPF
