### ISSUE TITLE
Prism Template Pack (Visual Studio 2019 Mac)

### ISSUE THREAD

**Issue by zg47** [PrismLibrary/Prism#1768] opened 2019-04-12 11:31 UTC
### Description

With the update to Visual Studio 2019 for Mac, our Prism Template Pack won't appear in the list of extensions anymore however, it does work as normal on Visual Studio 2019 on Windows..

### Steps to Reproduce

1. Visual Studio  -> Extensions -> Gallery
- Version with issue: Visual Studio 2019 Mac
- Last known good version: Visual Studio 2017 Mac
- Xamarin.Forms version: 3.6.0.293080

### Screenshots
![Screenshot 2019-04-12 at 12 17 32](https://user-images.githubusercontent.com/36827188/56034364-0a519980-5d1f-11e9-8457-87ff024058ea.png)

**Comment by dansiegel** [comment] 2019-04-12 11:56
Closed as duplicate of #1755

**Closed by dansiegel** 2019-04-12 11:56 UTC
