### ISSUE TITLE
Subpages of TabbedPage children opening in wrong tab navigation stack

### ISSUE THREAD

**Issue by lestersconyers** [PrismLibrary/Prism#1795] opened 2019-05-15 05:15 UTC
### Description
I'm trying to get Prism Navigation to work with a Tabbed page with Login page before hand. Getting to the Tabbed page is not a problem but I'm unable to go a level deeper. I also submitted this on to StackOverflow a few days ago. (https://stackoverflow.com/questions/56096837/xamarin-forms-prism-adds-page-to-wrong-tab-nav-stack)

### Steps to Reproduce

1. Update App.xaml.cs OnInitialized to navigate to a page (e.g. `NavigationService.NavigateAsync("/LoginPage");`)
2. From that pages View model, navigate to a TabbedPage with children wrapped in NavigationPage `await NavigationService.NavigateAsync($"/MainPage");`
3. Select a tab other than the first one
4. From that page's View Model call NavigateAsync to a relative page `await NavigationService.NavigateAsync(nameof(OneLevelDeeper));`

### Expected Behavior
OneLevelDeeper page should open in the currently selected tab's navigation stack
### Actual Behavior
Page opens in the navigation stack of the first tab
### Basic Information

- Version with issue: 7.1.0.431
- Last known good version: n/a
- Xamarin.Forms version: 3.6
- IDE: Visual Studio 2019 for Mac

**Comment by brianlagunas** [comment] 2019-05-15 13:18
Closing because there is no reproduction application. I you provide one, I will reopen.

**Closed by brianlagunas** 2019-05-15 13:18 UTC

**Comment by lestersconyers** [comment] 2019-05-15 17:41
Sure thing. I've tried several different variations and at this point, I can't get the OneLevelDeeper page to load in any tab at all. https://github.com/lestersconyers/prismtabbednavigation

**Comment by lestersconyers** [comment] 2019-05-15 20:37
Never mind. I found the issue. INavigationService needs to be instantiated for each class as opposed to a singleton. In my case, I was using a BasePageService pattern in my BaseViewModel to avoid injecting the same services in each ViewModel. However, INavigationService needs to be new for each ViewModel or else it believes that it is on the first page. In short, if you use BasePageService with NavigationService, do NOT register IBasePageService as a singleton. *womp womp womp*
