### ISSUE TITLE
[Enhancement] Move reference to Xamarin.Forms.Mocks to nuget/packageReference

### ISSUE THREAD

**Issue by dylanberry** [PrismLibrary/Prism#2057] opened 2020-04-14 23:15 UTC
## Summary

Within the test projects, move reference to Xamarin.Forms.Mocks to nuget/packageReference.

## API Changes

N/A

## Intended Use Case

Allow easier tracking and updates to the Xamarin.Forms.Mocks library.

**Comment by lv1il0s** [comment] 2020-04-22 18:27
I need a bit of clarification (I'm still a beginner in this domain, and I'm sorry if answer to my question seems obvious to others).

I found that there is a MockForms.cs file with a few classes within the Xamarin.Forms.Mocks namespace.

- Do you require moving this file into a separate class library project that should be maintained as a NuGet Package?
- If so, would it make sense to also separate classes into separate files for better readability and following "single type per file" convention?
- And how would you suggest populating NuGet Package's metadata (ID, Version, Authors, Description)? Are there some conventions to follow in this area?

Thanks in advance!

**Comment by dansiegel** [comment] 2020-04-22 19:05
@lv1il0s the issue is that when Prism for Xamarin.Forms started there was no package available. As a result Brian actually wrote the Xamarin.Forms.Mocks. Later Jonathan Peppers made it an official project which he maintains.

This issue to remove the Xamarin.Forms.Mocks from the Prism tests and then install the Xamarin.Forms.Mocks NuGet so that we are consuming it rather than maintaining it as part of the tests.

https://www.nuget.org/packages/Xamarin.Forms.Mocks/

**Comment by d3fkn1ght** [comment] 2020-04-23 10:48
@lv1il0s This link might help
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

**Comment by lv1il0s** [comment] 2020-04-23 23:19
Thanks for clarifying, @dansiegel!
And thanks for the tip, @d3fkn1ght!

I'll push the commit I made either tonight or tomorrow.

**Comment by dansiegel** [comment] 2020-04-23 23:20
@lv1il0s keep in mind there is a lot of activity right now, you'll want to be sure that your PR is rebased on master

**Comment by lv1il0s** [comment] 2020-04-23 23:28
Ok, I'll keep that in mind!

**Comment by dansiegel** [comment] 2020-04-24 17:26
fixed in #2091

**Closed by dansiegel** 2020-04-24 17:26 UTC
Labels: Good First Issue, XF, housekeeping
