### ISSUE TITLE
[Bug] [iOS] Prism.Forms DialogService ShowDialog 'breaks' Xamarin.Forms CollectionView in the background

### ISSUE THREAD

**Issue by jBijsterboschNL** [PrismLibrary/Prism#1936] opened 2019-10-22 20:32 UTC
### Description
My MainPage has a CollectionView, which shows a simple list. After opening a dialog with the new IDialogService, the CollectionView 'breaks' on the background (and also after closing the dialog). All cells inside the CollectionView are being rendered on top of the 'proper' rendering of the CollectionView (overlapping each other). This only happens when opening a custom dialog with the IDialogService of Prism.Forms and only on iOS, on Android this is not an issue. Making the CollectionView data template non transparent doesn't make a difference, as the improperly rendered cells of the CollectionView are being rendered on top of the properly rendered CollectionView.

### Steps to Reproduce

1. Add a CollectionView and a button (to trigger showdialog) to your page
2. Add a custom dialog and call IDialogService.ShowDialog() to open your custom dialog
3. In the background (and after closing your custom dialog), you'll see that the CollectionView is no longer rendered properly, as it shows all cells/rows/items on top of a properly rendered CollectionView.

### Expected Behavior
No change in the CollectionView being rendered when opening a custom dialog via the IDialogService.

### Actual Behavior
CollectionView rendering is 'broken' and all cells of the CollectionView are being rendered on top of each other after showing a custom dialog via the IDialogService.

### Basic Information

- Version with issue: Prism.Forms.Unity v7.2.0.1367
- Last known good version: N/A
- Xamarin.Forms version: Xamarin.Forms v4.3.0.908675 (thus stable version of CollectionView and not the experimental version, which also has the same behavior)
- IDE: Visual Studio 2019 v16.3.5

### Screenshots
Screenshot before ShowDialog():
![Before ShowDialog](https://i.ibb.co/1nj1RZD/Prism-Forms-Collection-View-rendered-properly-before-Show-Dialog.png)

Screenshot after ShowDialog():
![After ShowDialog](https://i.ibb.co/W2yn4wG/Prism-Forms-Collection-View-rendered-improperly-after-Show-Dialog-1.png)

Screenshot after ShowDialog() and RequestClose:
![After request close](https://i.ibb.co/rwfHbf9/Prism-Forms-Collection-View-rendered-improperly-after-Show-Dialog-2.png)

### Reproduction Link
[XForms.PrismDialog.CollectionViewBug](https://easyupload.io/er473v)

**Comment by jBijsterboschNL** [comment] 2019-11-05 07:23
@dansiegel does the 'blocked by platform' mean this is a Xamarin.Forms related issue? If yes, do you have some pointers or extra research information (that you might found during your research) I can send along to the Xamarin.Forms team?

**Comment by dansiegel** [comment] 2019-11-21 16:47
@jBijsterboschNL sorry, I thought I had replied to this. Yes the blocked by platform means it's actually a Xamarin.Forms issue. There seems to be an issue with their layout. When we update the layout it seems to be doing something very strange indeed.

**Comment by dansiegel** [comment] 2019-11-21 17:14
I'm actually going to close this issue. While I can 100% reproduce this with your sample, updating to the Xamarin.Forms 4.4 preview seems to fix it.

**Closed by dansiegel** 2019-11-21 17:14 UTC
Labels: XF
