### ISSUE TITLE
[Bug] Wrong text alignment of IPageDialogService.DisplayAlertAsync popup (Updated)

### ISSUE THREAD

**Issue by Alex-Dobrynin** [PrismLibrary/Prism#2316] opened 2021-01-22 21:47 UTC
**Descriprion:**
RTL - right to left, LTR - left to right
I need to show MasterDetailPage with RTL behavior, when flyout comes from right. But everything else I need to show with LTR.

When I trying to show some alert popup using IPageDialogService.DisplayAlertAsync, it shows popup like arabian style RTL.
I suppose its somehow relates to latest changes in prism 8x, because when prism was 7.2.x I didnt notice such behavior of popups.

If I use UserDialogs popups it shows popup with proper text alignment.

**Expected result:** 
the flow direction of prism's popups should be taken from application language preferences or app settings, or could be customizable

**Actual result:** 
the flow direction of prism's popups is inherited from root page of an app

**Basic information:**
Prism 8, XF 5

**Project to reproduce:**
Here is project which reproduces this bug:
[Issue2309.zip](https://github.com/PrismLibrary/Prism/files/5858775/Issue2309.zip)

**Comment by dansiegel** [comment] 2021-01-27 15:25
This is not a bug, however the Xamarin.Forms team has added some new method overloads that include FlowDirection. This is something that we'll need to evaluate for an updated API in Prism 8.1

**Comment by dansiegel** [comment] 2021-03-24 20:26
This is resolved and will be in the next release

**Closed by dansiegel** 2021-03-24 20:26 UTC
Labels: XF, enhancement
