### ISSUE TITLE
[Enhancement] IDialogAware enhancement

### ISSUE THREAD

**Issue by sylvesp** [PrismLibrary/Prism#1986] opened 2020-01-01 17:44 UTC
## Summary

When displaying a **dialog with child Regions** using _IDialogService.ShowDialog()_, the _ViewModel_ of the dialog implementing _IDialogAware_ gets the _OnDialogOpened()_ call **BEFORE** the View Models of the children regions are created.
Because of this there is no 'elegant/straight forward' way to pass on the dialog parameters to the ViewModels of the child regions.

## API Changes

Have the _IDialogAware.OnDialogOpened()_ be called **AFTER** the ViewModels of all the children regions have been created

**OR**

Add a new method to _IDialogAware_ that is called when the dialog is ready to be displayed with all the child _ViewModels_ initialized.

e.g.

```
public interface IDialogAware
{
  ...
   void BeforeDialogDisplayed();
  ...
}

public class MyDialogViewModel: BindableBase, IDialogAware
{
  private IDialogParameters DialogParameters {get; set;}

  public MyDialogViewModel(IEventAggregator eventAggregator)
  {
     _eventAggregator = eventAggregator;
  }
  public void OnDialogOpened(IDialogParameters parameters)
  {
     DialogParameters = parameters;
  }
  public void BeforeDialogDisplayed()
  {
  //now the children regions are already created and listening to this event
    _eventAggregator.GetEvent<IDialogParameters>().Publish(DialogParameters);
  }
}
```

**Comment by brianlagunas** [comment] 2020-01-07 17:30
Unfortunately this is not possible. The dialog will never know how many regions yo have, if or when those regions have views in them, or if the ViewModels of the views within those regions have been created and assigned to the DataContext of those views.  In this case, you may want to consider passing your parameter using another method such as the RegionContext.  Or, have the IDialogAware VM perform the navitation to the region in the OnDialogOpened and pass the parameters forward.

**Closed by brianlagunas** 2020-01-07 17:30 UTC
Labels: WPF, enhancement

**Comment by sylvesp** [comment] 2020-01-07 20:58
Sorry :( Sounds that I was not clear enough. 
The problem is that OnDialogOpened() is being invoked BEFORE the constructor of the Region's VM.
Would it be possible to navigate to the region when it was not yet created?

With my original thought the dialog does not have to know about its regions at all. 
Just that the Regions have to be created BEFORE the OnDialogOpened() call.
In such a case the regions - when created - would subscribe for a "update your parameters" event which would published by the dialong when the OndialogOpened() comes. 
Again: the dialog wouldn't know about its regions, it would just publish the event with the dialog parameters to whoever is listening for it - in this case the listeners would be the already created regions.

Will give a shot to passing the parametes through the RegionContext and let you know if I run into other trouble.

**Comment by brianlagunas** [comment] 2020-01-07 21:24
@sylvesp In order for this to work, the dialog would need to know when the regions have been created, which is not possible. You are complicating a simple task. Just navigate your regions in the OnDialogOpened, and pass your parameters.

**Comment by sylvesp** [comment] 2020-01-10 16:03
Well.. I did try to navigate to the region inside the dialog during the OnDialogOpened AND also After the OnDialogOpened call.
It turns out that there are more issues with **Dialogs containing Regions** than I've thought.

The main problem seemingly is that:
**- The Prism RegionManager is completely Unaware of regions that are contained in Dialogs**

To illustrate,  I've attached a sample project that contains a MainWindow, a SampleDialog and a Sample region.

To reproduce the issue:
- compile and run the solution
- in the MainWindow click the "Show Dialog" button => you will see a message saying that at the time of OnDialogOpened the region manager knows of 0 (zero) regions
- In the dialog that shows up click the "Show Number of existing Regions" => result will be the same: 0
- When you click the "Show Number of existing Regions" the dialog will also try to navigate to the SampleRegion - but no success.
-----------
Now in the MainWindow.xaml you can uncomment the part that will place a region into the MainWindow and run the application again.
- In this case the region manager will know about a region, but if you invoke the SampleDialog and click the "Show Number of existing Regions" - this will navigate to the region in the main window and NOT to the region in the dialog.

-----------------
Well that's it. Please let me know if I am doing something wrong.
Thanks
Peter

[Prism_DialogRegions.zip](https://github.com/PrismLibrary/Prism/files/4046460/Prism_DialogRegions.zip)
 :(

**Comment by brianlagunas** [comment] 2020-01-10 17:05
This is by design, you need to assign the region manager to your dialog when it is created.

I covered these issues in a number of streams:
https://youtu.be/ZtYC0O2jayE
https://youtu.be/lJjl3KrCPu0
https://youtu.be/ZwYjHxy7YbU
