### ISSUE TITLE
[Win 10 UAP] Issue with device specific views

### ISSUE THREAD

**Issue by Rhywden** [PrismLibrary/Prism#130] opened 2015-09-08 09:30 UTC
In Win10 UAP if you're unable to create an adaptive view for some device families, you're allowed to create specific views just for that family.

In my case, the main page on the desktop shows three gridviews directly below each other, with the items stretching horizontally. On mobile, this won't work for obvious reasons and thus I'd like to switch to a pivot control for the mobile view.

Now, one of the easiest ways to create such a view is to simply create a new folder (DeviceFamily-Mobile in this case) and drop a pure XAML file (without an attached XAML.cs) named like the original view.

So, if the main page was called MainPage.xaml, then I'd also have a MainPage.xaml in this new folder. Depending on the device, the views are supposed to be exchanged upon startup.

This does work when I start the project inside the mobile simulator - it doesn't work when I start the project on Local Machine, i.e.my desktop with the following runtime error:

    public MainPage()
        {
            this.InitializeComponent(); // this one throws the exception
        }

     XAML parsing failed.

     at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
     at CourseBook2015.Views.MainPage.InitializeComponent(Uri resourceLocator)
     at CourseBook2015.Views.MainPage.InitializeComponent()
     at CourseBook2015.Views.MainPage..ctor()
     at CourseBook2015.CourseBook2015_XamlTypeInfo.XamlTypeInfoProvider.Activate_24_MainPage()
     at CourseBook2015.CourseBook2015_XamlTypeInfo.XamlUserType.ActivateInstance()

If I delete the DeviceFamily-Mobile folder, then everything goes back to how it was before.

**Comment by briannoyes** [comment] 2015-09-08 11:00
If you can provide a small repro of the problem and point us to the guidance around how this is supposed to work, we will look into it.

**Comment by Rhywden** [comment] 2015-09-08 17:15
Okay, I zipped up a solution (sorry if I put more in that than I should - I simply compressed the whole folder), [which can be found here](https://onedrive.live.com/redir?resid=89F3132E06619076!69237&authkey=!APotTQ6-_N3O7a0&ithint=file%2czip).

How it's supposed to work is probably more comprisingly [described here](http://igrali.com/2015/08/02/three-ways-to-set-specific-devicefamily-xaml-views-in-uwp/) (and also the alternative ways to get there). 

As I said, you can switch between the two expected views by simply deleting the mobile-family folder (if it's there the mobile view works, if it isn't the desktop view works)

**Comment by briannoyes** [comment] 2015-10-12 16:42
This does not appear to be a Prism problem, more of a platform/tooling one. I can repro the problem by:
1. New Universal app project
2. Add DeviceFamily-Mobile folder and add a MainPage.xaml as a XAML View into that folder.
3. Move MainPage.xaml (with code behind - created by project template) into a \Views subfolder and change its namespace to include .Views.
4. Change the namespace of the mobile version view to match.

I'm a Windows Platform MVP and can get a message to the platform team so they are aware, but closing this here since it is reproducible with no Prism in the solution at all.

**Closed by briannoyes** 2015-10-12 16:42 UTC

**Comment by briannoyes** [comment] 2015-10-12 17:16
Oh, and more information - simple workaround - the DeviceFamily-Mobile directory just needs to be a subfolder of whatever folder/namespace the desktop/root view is defined in, so move that folder under the Views folder and it works fine.

**Comment by haifaGh** [comment] 2016-04-05 22:20
hi , can we change the layout in the same family device ? meaning i want to create different designs for 4" and 5" : i don't want them to look the same ... is that possible ?

**Comment by jiji2** [comment] 2016-04-05 22:22
hi , can we change the layout in the same family device ? meaning i want to create different designs for 4" and 5" : i don't want them to look the same ... is that possible ?
