### ISSUE TITLE
[Bug] TabbedPage.CurrentPage results in NullReferenceException

### ISSUE THREAD

**Issue by Gh0stC0de** [PrismLibrary/Prism#1976] opened 2019-12-20 08:27 UTC
### Description

Navigation to a tabbed page with no tab results in a NullReferenceException.

### Steps to Reproduce

1. Register a TabbedPage with no tabs
2. Navigate to the registered TabbedPage

### Expected Behavior
No errors.

### Actual Behavior
The ILoggerFacade logs a NullReferenceException.
See console output in reproduction project:
-> Exception|High|System.NullReferenceException: Object reference not set to an instance of an object. [...]

### Basic Information

- Version with issue: 7.2.0.1422 and also 8.0.0-ci
- Last known good version: N/A
- Xamarin.Forms version: 4.4.0.991265
- IDE: VisualStudio 16.4.2

### Reproduction Link

https://github.com/Gh0stC0de/SampleBugApp

**Comment by Gh0stC0de** [comment] 2019-12-20 08:41
I don't know how to create a pull request for this but a possible fix would be:

Changing this:
`else if (tabbedPage.BindingContext != tabbedPage.CurrentPage.BindingContext)`

to this:
`else if (tabbedPage.BindingContext != tabbedPage.CurrentPage?.BindingContext)`

in [PageNavigationService](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L750)

**Comment by dansiegel** [comment] 2019-12-20 15:43
This is a duplicate of #1959. We currently have no intention of "fixing this" as this tells me you are doing something extremely wrong here and you should be encountering an exception. Remember you can dynamically build your TabbedPages as shown here.

```cs
protected override void OnInitialized()
{
    NavigationService.NavigateAsync("TabbedPage?createTab=ViewA&createTab=ViewB");
}

protected override void RegisterTypes(IContainerRegistry containerRegistry)
{
    containerRegistry.RegisterForNavigation<TabbedPage>();
    containerRegistry.RegisterForNavigation<ViewA>();
    containerRegistry.RegisterForNavigation<ViewB>();
}
```

**Closed by dansiegel** 2019-12-20 15:43 UTC
Labels: XF
