### ISSUE TITLE
Prism depends on System.Windows.Interactivity

### ISSUE THREAD

**Issue by znakeeye** [PrismLibrary/Prism#1963] opened 2019-12-09 12:37 UTC
In 2019 we use [Microsoft.Xaml.Behaviors.Wpf](https://github.com/microsoft/XamlBehaviorsWpf) instead.

So please get rid of that DLL and update your namespaces. Prism users should use that NuGet package from now on.

**Comment by brianlagunas** [comment] 2019-12-09 15:02
Duplicate of #1897

**Closed by brianlagunas** 2019-12-09 15:02 UTC
