### ISSUE TITLE
Castle Windsor IoC support

### ISSUE THREAD

**Issue by benlaan** [PrismLibrary/Prism#791] opened 2016-10-04 01:39 UTC
I am interested in developing Castle Windsor IoC support for Prism.Wpf.

Is there anything I should know before I start? - i.e. is someone already working on it?

**Comment by brianlagunas** [comment] 2016-10-04 01:50
No one is working on it, but I'm not sure that is a container that we want to add to the Prism repo.  I don't see a lot of demand for that container within the WPF community.

Anyone else using this container?

**Comment by brianlagunas** [comment] 2016-10-14 02:13
I am closing this because it is not a container that we feel has enough adoption to warrant adding it to the library.  Fortunately it is very easy to add support for this container for use in your own project.

**Closed by brianlagunas** 2016-10-14 02:13 UTC

**Comment by benlaan** [comment] 2016-10-18 00:17
That's fine. If anyone ever stumbles upon this, contact me for my version

**Comment by brianlagunas** [comment] 2016-10-18 01:13
sounds good

**Comment by TaviTruman** [comment] 2016-12-18 06:33
I know this issue has been closed but we have been looking around at using another IoC other than Unity or other existing IoC that Prism support; we like Castle Windosr IoC very much. Brian we would be interested in getting this to work as Unity looks to End of Life.

**Comment by bartlannoeye** [comment] 2016-12-18 07:38
There's no reason to bring out new releases if the curent release "just works". That's the stage Unity is currently in: it works.

We're not adding in new IoC framworks because of our limited time to spend on Prism and there are more important issues to handle. You could ping @benlaan for his version or add support yourself if for some reason you're stuck to Castle Windsor and can't use any of the supported containers.

**Comment by marcel-Ngan** [comment] 2018-02-20 09:39
@benlaan Are you still using Castle.Windsor with Prism? I've just started with it and am experiencing any issue. Is there any method I can contact you to discuss them?

**Comment by TaviTruman** [comment] 2018-02-20 20:57
@marcel-Ngan we have a clean working integration of Castle Windsor through the current release; what type of problems are you having. We might be able to help.

**Comment by marcel-Ngan** [comment] 2018-02-21 03:46
@TaviTruman I manage to get the issue working. Was just some dependency that I forgot to register. I was wondering if there is any examples like the WPF-examples on here for Castle.Windsor?

**Comment by TaviTruman** [comment] 2018-02-21 17:31
@marcel-Ngan There aren't any WPF Prism+Castle.Windsor examples; which is interesting as Castle Windsor was one of the first IoC technologies for .NET and Prism.

**Comment by brianlagunas** [comment] 2018-02-21 17:38
@TaviTruman That statement is incorrect. Castle Windsor has never been an officially supported Prism container. The container you use has no impact on the Prism APIs or how you use Prism (except in the case of MEF, which isn't a container or supported anymore). Container specific samples make no sense unless you do not know how to use the container you have selected.

**Comment by marcel-Ngan** [comment] 2018-02-21 17:48
@brianlagunas True, I'm still looking at the WPF examples and they seem to be alright. The biggest issue I think is how to make the windsor bootstrapper work.

**Comment by TaviTruman** [comment] 2018-02-21 17:54
@brianlagunas That's true - I was only mentioning that the Castle Windsor technology has been around for a long time, and I don't think I made or hold Prism at fault for not directly supporting the container. The fact is you won't find any examples or samples of WPF or any such technology at the Castle GitHub site either. One of the first examples I found of using Castle Windsor IoC With Prism was in MSDN issues from 2010 and 2013. Castle Windsor has been around for along time (a large, very sophisticated and powerful IoC technology) and like the others containers used by WPF/PRISM developers is alive, active and well supported. One of the beautiful things I love about Prism is that the technology is one of choice and is very flexible by design.

**Comment by TaviTruman** [comment] 2018-02-21 18:03
@marcel-Ngan We have a very sophisticated WPF app based on Prism 6.3 with Castle Windsor that makes use of Multi-Shells extension; I'd be willing to share with your some of the idioms and techniques w.r.t. Castle Windsor and bootstrapper, and related technical matters.

**Comment by marcel-Ngan** [comment] 2018-02-21 18:09
@TaviTruman are you using custom built bootstrapper or something that's found in the internet?

**Comment by marcel-Ngan** [comment] 2018-02-26 05:03
@TaviTruman any chance we can talk on Skype or some other communications method. Just some basic issues that I'm trying to sort out for now. (Mainly the difference between using Castle.Windsor and Unity from looking at the examples)

**Comment by TaviTruman** [comment] 2018-02-26 05:18
@marcel-Ngan Certainly - you can reach me @ tavi@inknowworks.com; we can establish means to communicate once you send me an email.

**Comment by multinerd** [comment] 2019-09-23 19:50
> 
> 
> That's fine. If anyone ever stumbles upon this, contact me for my version

Hi @benlaan, I am hoping you can share your implementation on  `RegionNavigationContentLoader`. I seem to be having trouble resolving named instance.
