### ISSUE TITLE
7.0.0.336-pre not resolving NavigationPage

### ISSUE THREAD

**Issue by Bjselous** [PrismLibrary/Prism#1311] opened 2017-12-22 02:52 UTC
I upgraded to 7.0.0.336-pre and the project now throws the following exception on startup:

DryIoc.ContainerException: Unable to select single public constructor from implementation type Xamarin.Forms.NavigationPage:
Void .ctor(), 
Void .ctor(Xamarin.Forms.Page)
   at DryIoc.Throw.It(Int32 error, Object arg0, Object arg1, Object arg2, Object arg3)
   at DryIoc.ReflectionFactory.ThrowIfInvalidRegistration(Type serviceType, Object serviceKey, Boolean isStaticallyChecked, Rules containerRules)
   at DryIoc.Container.Register(Factory factory, Type serviceType, Object serviceKey, IfAlreadyRegister

This behavior appears to be related to NavigationPage only because if I edit App.xml.cs as follows:

`  public App(IPlatformInitializer initializer) : base(initializer) { }

        protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
            //containerRegistry.RegisterForNavigation<NavigationPage>();
            containerRegistry.RegisterForNavigation<MainPage>();
        }

        protected override async void OnInitialized()
        {
            InitializeComponent();
            
           //await NavigationService.NavigateAsync("NavigationPage/MainPage"); 
            await NavigationService.NavigateAsync("MainPage");
        }` 

This will load MainPage without issues. 

Is this a bug or am I missing something when I upgrade to 7.0.0.336-pre?

### Package info

- Platform: UWP (throws DryIoc.ContainerException: Unable to select single public constructor from implementation type ), 
Android (throws DryIoc.ContainerException: <Timeout exceeded getting exception details>) and 
iOS (throws DryIoc.ContainerException: Unable to select single public constructor from implementation type )
- Prism version:7.0.0.336-pre
- Xamarin version (if applicable): Xamarin.Forms 2.5.0.121934
- Windows 10 SDK version (if applicable):  16299
- Other version info: DryIoc 2.12.5

### Repro steps

1. Create new project using prism template pack version 2.0.7 (latest)
2. Update nugets ()
3. Update Prism.DryIoc.Forms to 7.0.0.336-pre
4. Refactor to import IPlatformInitializer and implement RegisterTypes(IContainerRegistry containerRegistry)
5. Refactor page registration containerRegistry.RegisterForNavigation<NavigationPage>();

Run. 

Expected behavior: App runs, NavigationPage resolved. 
Actual behavior: Exception on startup DryIoc.ContainerException: Unable to select single public constructor from implementation type

**Comment by dansiegel** [comment] 2017-12-22 03:13
this is a duplicate of #1304. You can use the package in the CI feed for the fix to this issue.

**Closed by dansiegel** 2017-12-22 03:13 UTC
