### ISSUE TITLE
Deep navigation looses navigation header

### ISSUE THREAD

**Issue by hardcodet** [PrismLibrary/Prism#937] opened 2017-02-05 14:23 UTC
Xamarin Forms: Assume I'm at my home page, which has the following page hierarchy:

MasterDetailPage/NavigationPage/HomeContentPage

- From here, if I navigate to URI "FOO", then the FOO page is being displayed with a navigation header, which allows me to go back to HOME. Instead of going back, I can also navigate to "BAR". In that case, the BAR page is displayed, again with a navigation header, that allows me to go back to "FOO". So far so good.

- However:  If I navigate directly to URI "**FOO/BAR**" from the home page, I end up with the BAR page, but the navigation header is missing. If I tap the back button (on Android, I'm stuck in iOS), the FOO page is displayed, which again with the expected navigation header.

**Comment by hardcodet** [comment] 2017-02-05 14:36
Oh, it's noteworthy that if I use an absolute URI instead of a relative one, the headers are there.

So this works:
    `/MasterDetailPage/NavigationPage/HomeContentPage/Foo/Bar`

This doesn't:
    `Foo/Bar`

**Comment by brianlagunas** [comment] 2017-02-05 16:59
This is a known issue (duplicate of #765).  It is a bug in Xamarin.Forms and you can monitor the progress of the bug here: https://bugzilla.xamarin.com/show_bug.cgi?id=44115

**Closed by brianlagunas** 2017-02-05 16:59 UTC
Labels: XF

**Comment by hardcodet** [comment] 2017-02-06 01:38
No, that's actually another bug (which I'm also seeing):

This results "only" in the wrong title in the header (the bug you linked to):
`/MasterDetailPage/NavigationPage/HomeContentPage/Foo/Bar`

This results in the header missing completely, so there's also no means to pop the view on iOS:
`Foo/Bar`

**Comment by brianlagunas** [comment] 2017-02-06 01:42
You won't get a toolbar or software back button unless your views are wrapped in a NavigationPage.  This is how XF works.

**Comment by hardcodet** [comment] 2017-02-06 09:14
I know, but there is a Nav Page in my stack. I'm starting with this stack:

/MasterDetailPage/**NavigationPage**/HomeContentPage/

If I navigate to "Foo" and then from "Foo" to "Bar", I end up with the header. If I navigate directly to "Foo/Bar", the header is completely missing. In both case, my stack hierarchy is 

/MasterDetailPage/**NavigationPage**/HomeContentPage/Foo/Bar

**Comment by brianlagunas** [comment] 2017-02-06 15:24
Try setting the useModalNavigation = false when you navigate.

**Comment by hardcodet** [comment] 2017-02-07 11:32
Damn, that did the trick. I would have never thought the last view in the stack would be displayed modal. Thanks!

**Comment by hardcodet** [comment] 2017-02-07 12:37
Correction: I didn't check the UI right. Actually, this is an even worse bug: If I navigate to "Foo/Bar", I end up with two times Foo on the stack. The top-level Foo is initialized properly. When I pop it, I get to a non-initialized Foo (no bindings executed etc.). Popping that erroneous Foo gets me back to where I came from.
I guess I'll stick to absolute navigation for now and simply recreate the root views every time.

**Comment by brianlagunas** [comment] 2017-02-07 15:05
Yes, you are seeing a combination of two Xamarin.Forms bugs.

https://bugzilla.xamarin.com/show_bug.cgi?id=45978
https://bugzilla.xamarin.com/show_bug.cgi?id=44115

I have been waiting for Xamarin to fix these for a long time.  They haven't fixed them yet.
