### ISSUE TITLE
Nuget Prism.Unity throw error "'.', hexadecimal value 0x00, is an invalid character."

### ISSUE THREAD

**Issue by Cuiqs76** [PrismLibrary/Prism#261] opened 2015-10-25 15:34 UTC
VS2015 & Windows 10 environment Nuget the Prism.Unity throw Error "hexadecimal value 0x00, is an invalid character."

Attempting to gather dependencies information for package 'Prism.Unity.6.1.1' with respect to project 'MonitorDemo', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'Prism.Unity.6.1.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Prism.Unity.6.1.1'
Resolved actions to install package 'Prism.Unity.6.1.1'
Install failed. Rolling back...
Package 'Prism.Unity 6.1.1' does not exist in project 'MonitorDemo'
Package 'Prism.Unity 6.1.1' does not exist in folder 'E:\MonitorDemo\packages'
System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream)
   at NuGet.Packaging.Core.NuspecCoreReaderBase..ctor(Stream stream)
   at NuGet.Packaging.NuspecReader..ctor(Stream stream, IFrameworkNameProvider frameworkProvider)
   at NuGet.Packaging.NuspecReader..ctor(Stream stream)
   at NuGet.Packaging.PackageReaderBase.get_Nuspec()
   at NuGet.Packaging.PackageReaderBase.get_NuspecCore()
   at NuGet.Packaging.Core.PackageReaderCoreBase.GetIdentity()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Finished ==========

**Comment by briannoyes** [comment] 2015-10-25 17:49
Will need a repro, its working fine in all the apps I have created with it so far.

**Comment by brianlagunas** [comment] 2015-10-25 18:37
I am also not able to reproduce the error.  I am closing this until it can reproduced consistently.

**Closed by brianlagunas** 2015-10-25 18:37 UTC
