### ISSUE TITLE
Xamarin.Forms iOS: TabbedPage Children's INavigationAware

### ISSUE THREAD

**Issue by haythamnikolaidis** [PrismLibrary/Prism#1293] opened 2017-12-01 09:46 UTC
### Package info

- Platform: iOS 11.1
- Prism version: 6.3
- Xamarin version (if applicable): Xamarin.iOS: 11.3.0.47 Xamarin.Forms 2.5.0

### Repro steps

Example Project to reproduce the behaviour: [https://github.com/haythamnikolaidis/ImbeddedNavigationIssue-](https://github.com/haythamnikolaidis/ImbeddedNavigationIssue-)

When creating a TabbedPage in Xamarin.Forms on iOS that has more then 5 tabs the TabbedPage creates a "More" tab with a list view to select the tabs from 5 and up. 

For tabs in this "More" list (and only in this list) the INavigationAware callbacks are not fired on back navigation (Navigation Bar back button or INavigationService.GoBackAsync()). However they are fired as expected in tabs that are not in the "More" list.

In the above example app, once its open on any of the first four tabs and tapping the NavigateToDetails button, upon navigating back, NavigatedTo is fired and the label is updated on screen.

However doing the same in the last three tabs, results in the NavigatedTo not being fired and the label not being updated on screen.

**Comment by brianlagunas** [comment] 2017-12-06 20:53
Thanks for reporting this.  It seems iOS handles overflow tabs differently than normal tabs. I'll have to look into the cause of this and see if there is a way to fix it.

**Comment by brianlagunas** [comment] 2017-12-06 21:08
Turns out that the TabbedPage.CurrentPage is null on iOS when in the "More" group. I'm not sure this can be fixed as I don't see a way to access the current tab.  Let me dig around and see what I can find.  If you have any ideas on how to approach this, please feel free to throw out your ideas.

**Comment by dansiegel** [comment] 2017-12-06 21:30
For starters I would say you should not use OnNavigatedTo for any child of a TabbedPage. OnNavigatingTo should be called if you update to Prism 7. 

Next I suggest updating to use IPageLifecycleAware as it will trigger OnAppearing after OnNavigatingTo has been called allowing you to respond to the fact that it is the active page. IActiveAware has the flaw that it will set IsActive to true prior to OnNavigat{ing|ed}To being called which can be problematic for your first page. It also will set IsActive to true for the first child, then update it to false before setting the next child to true when changing the Selected Tab via the navigation service and again before they have been initialized.

**Comment by brianlagunas** [comment] 2017-12-06 21:39
@dansiegel Your statements are not 100% accurate.  The OnNavigatedTo should be called when going back or navigating to a TabbedPage tab.  There is a bug in XF in that the Currentpage is null when the tabs exist in the iOS "more" group.  Even the CurrentPageChanged event does not fire. This means there is no way to determine the delected tab when the tabs exist in the "more" group.

This also means that `IActiveAware` won't work as well as the new `selectedTab` parameter feature.  While a work around would be to use the IPageLifeCycleAware, that does not fix the other scenarios and that does not support parameters.

I'm going to report this to Xamarin.

**Comment by dansiegel** [comment] 2017-12-06 21:50
@brianlagunas, I’m not saying it isn’t currently supposed to be called, I’m saying it shouldn’t be used. It will inevitably lead to code design that will result in buggy behavior because it may not be consistent as to when your code executed. For example did you select the tab as the initial tab when navigating or from the user selecting it through the UI? 

Even without the issue from Xamarin, IActiveAware can create problems. For instance can your `IsActive == true` code execute when you haven’t initialized your ViewModel? You also then have to make sure you go back and get that code to execute once you’ve completed your initialization in OnNavigatingTo. It’s just a lot of unnecessary code that is easily solved by taking the path I outlined above.

**Comment by brianlagunas** [comment] 2017-12-06 21:56
>  I’m saying it shouldn’t be used

This is bad advice and you should not be giving it.  INavigationAware is used for different scenarios than detecting tab changes.  The scenario in this issue is coming back from a page, the OnNavigatedTo should fire.  Each feature has a use case. The features are mutually exclusive.

**Comment by brianlagunas** [comment] 2017-12-06 22:37
I have reported this bug to Xamarin, and will update this issue when a fix has been provided:

https://github.com/xamarin/Xamarin.Forms/issues/1336

**Comment by dansiegel** [comment] 2017-12-07 03:04
> INavigationAware is used for different scenarios than detecting tab changes.
@brianlagunas I'm very aware of that. I'm sorry you feel it's bad advice, but I think you're wrong on this. While there may be some edge cases where it may make sense to use the INavigatedAware part of INavigationAware within a child of a TabbedPage, I see this causing more problems than it solves unless you can be sure of which tab is being NavigatedTo you are far better off handling OnNavigatedTo at the TabbedPage level. For one you're likely going to have a bunch of duplicated code, or you may be calling OnNavigatedTo on the wrong tab, or you may not update another tab that needs to be updated...

**Comment by brianlagunas** [comment] 2017-12-07 03:39
> but I think you're wrong on this

This makes me laugh. Besides writing this from the ground up, you obviously know that I have a vast understanding of the various navigation scenarios to know that INavigationAware is not just an edge case feature. To say otherwise is a misrepresentation of the Prism guidance.  INavAware is not meant for tab changes. IPageLifecycle is not a replacement for INavAware or IActiveAware. The scenario you have in your mind being used to support your position is just one of many.  Your statement is wrong, and will not be an officially supported statement.

**Comment by haythamnikolaidis** [comment] 2017-12-08 13:43
@brianlagunas Thank you for the help, I will keep my eye on the Xamarin bug report.

**Comment by dansiegel** [comment] 2019-06-06 22:42
Adding a Help Wanted for this issue. This is a Xamarin.Forms issue, however this issue is up for grabs for anyone in the community that would like to help fix the issue directly in Xamarin.Forms. Please see the xamarin/Xamarin.Forms#1336 issue

**Comment by brianlagunas** [comment] 2021-05-10 22:33
After 4 years, we have come to the conclusion that Xamarin will not fix this. Closing because it pointless to have this open 😄

**Closed by brianlagunas** 2021-05-10 22:33 UTC
Labels: XF, blocked by platform, bug

**Comment by haythamnikolaidis** [comment] 2021-05-11 06:25
Thanks for hanging onto this for so long @brianlagunas 😂
