### ISSUE TITLE
[Bug] An unexpected error occurred while resolving 'Prism.Navigation.INavigationService'

### ISSUE THREAD

**Issue by kerbooo** [PrismLibrary/Prism#2270] opened 2020-12-09 13:06 UTC
Hello, I am using **Prism Forms **8.0.1909.**** After adding as following line for using **Prism.Plugin.Popups **7.2.0.1046**** 

```
protected override void RegisterTypes(IContainerRegistry containerRegistry)
{
	containerRegistry.RegisterPopupNavigationService();
	....
}
```

I am getting as following error
`
Prism.Ioc.ContainerResolutionException: 'An unexpected error occurred while resolving 'Prism.Navigation.INavigationService''`

After remove `containerRegistry.RegisterPopupNavigationService();` line, I am not getting any error.

Thank you in advance for your help.

**Comment by dansiegel** [comment] 2020-12-09 14:43
Your issue is not with Prism but rather the Popup Plugin. Closing this as a duplicate of the issue there.

**Closed by dansiegel** 2020-12-09 14:43 UTC
Labels: bug, to verify

**Comment by MauricioCodeguez** [comment] 2021-01-14 02:59
@kerberosargos I am having the same issue here. Have you found a solution?

**Comment by markrobert194** [comment] 2021-03-01 15:16
Any solution to this problem?

**Comment by kerberosargos** [comment] 2021-03-01 15:57
hello @markrobert194 @dansiegel have added beta version of plugin to [Nuget](https://www.nuget.org/packages/Prism.Plugin.Popups ). You can install package from VS as following picture
  
![Ekran Alıntısı](https://user-images.githubusercontent.com/11364304/109522861-c822d400-7abf-11eb-8e71-eefd642bc955.PNG)

**Comment by kerberosargos** [comment] 2021-03-01 21:40
> 
> 
> @kerberosargos I am having the same issue here. Have you found a solution?

Hello @MauricioCodeguez I am sorry I saw your question very late.
