### ISSUE TITLE
[UWP] Support auto-wiring viewmodel for Shell

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#1090] opened 2017-06-19 08:03 UTC
Currently the CreateShell (to have split view / hamburger menu) doesn't support auto-wiring viewmodel for the shell page.

For the SplitViewSample where we did inject a usercontrol in the pane, this wasn't much of an issue. However moving to the HamburgerMenu control from UWP toolkit, the shell page needs a view model to bind all primary/secondary menu items.

**Comment by wowfood** [comment] 2017-09-11 11:26
Could you expand on this?  

I haven't played with UWP yet, but in the WPF version at least you can autobind the viewmodel to the shellview during startup without issue.

If I'm guessing right, and the issue is that the second control you're trying to use hasn't been registered with the IoC container yet, then the easiest way around this is to just defer loading these.

Create your shellview with multiple regions (hamburger region, content region in this example) but with nothing actually in (just the layout logic)

Start up application with a shell and vm (nothing loaded) do all your bindings (i created a loading page so users can see something is happening) once things are bound, you then navigate to the hamburger control, in the hamburger region.

**Comment by brianlagunas** [comment] 2018-09-26 01:03
This should be fixed now

**Closed by brianlagunas** 2018-09-26 01:03 UTC
Labels: UWP
