### ISSUE TITLE
GoBackAsync not firing OnNavigatedTo

### ISSUE THREAD

**Issue by v1rtu41m4n** [PrismLibrary/Prism#977] opened 2017-03-11 02:13 UTC
I have a problem with the navigation service on version 6.3 when I call `_navigationService.GoBackAsync(navParams)` it does not fire the OnNavigatedTo. is there any way to notify the page that it had parameters on return?

**Comment by brianlagunas** [comment] 2017-03-11 02:15
You need to submit a repro with this.  I am unable to reproduce this issue.  This is working fine on the app I am running right now.

**Comment by v1rtu41m4n** [comment] 2017-03-11 02:55
### Package info

- Platform: Android API 23
- Prism version: 6.3.0-pre3
- Xamarin version: 2.3.3.193

### Repro steps

1. I have a MasterDetail Page
2. From Master I navigate to a TabbedPage that host two pages (ViewA and ViewB) this navigation was performed invoking a navigation command from the master in this way 'await _navigationService.NavigateAsync(target);' where target equals 'NavigationPage/TabbedPage/ViewA' to keep the master detail visible
2. On ViewA I have a ListView with a collection of items, the user tap on an item selecting it and fire a View C to see the details `await _navigationService.NavigateAsync(nameof(PhotoPage), navParams, false);` (the useModalNavigation was set to false to show the native back button to the user)
3. On ViewB the user do an action that need to be notified to the ViewA on navigating back when it call 'var navParams = new NavigationParameters();
						navParams.Add("ParamName", ParamObject);
						await _navigationService.GoBackAsync(navParams);'
4. When ViewA is showed to the user it does not fire neither 'OnNavigatedTo' nor  'OnNavigatingTo' events

If I do not set "useModalNavigation" flag it works but I need to show the native back button to the user to navigate back in case that he do not do anything on ViewB

**Comment by brianlagunas** [comment] 2017-03-11 03:04
Please create a repo app.

**Comment by brianlagunas** [comment] 2017-03-11 03:08
You can either place it on GitHub or in a zip file. This will make it easier, and faster,  for me to look into.

**Comment by brianlagunas** [comment] 2017-03-11 03:13
Also, if you implement INavigationAware on the TabbedPage, does it fire?

**Comment by v1rtu41m4n** [comment] 2017-03-11 03:13
I am sorry but what you you mean of "Repo app" I don't know what to do :s

**Comment by v1rtu41m4n** [comment] 2017-03-11 03:24
If I implement INavigationAware on the TabbedPage it was fired, is there any way to wire up this event to the ViewA???

**Comment by brianlagunas** [comment] 2017-03-11 03:50
A repro app is a simple application that reproduces the issue. Something ready for me to run and see the issue to make it easier to debug and fix.

**Comment by v1rtu41m4n** [comment] 2017-03-11 04:14
oh OK. with the project that I currently working on is not possible because the confidentiality agreement with our client, but I will try to create a simple demo to reproduce this, in the meantime I do a workaround and implement an event to do notification between the vm's

**Comment by brianlagunas** [comment] 2017-03-13 15:53
I was able to duplicate your issue using your repro steps.  You have uncovered a very interesting scenario.  I must decide how the OnNavigatedTo works when going back.  It looks like we need to call OnNavigatedTo on both the parent and the child pages on a GoBackAsync.  For example, if I am going back to a MasterDetailPage, I need to call OnNavigatedTo on both the MasterDetailPage and the Detail because I don't know exactly what the target is.  Same goes for TabbedPage and CarouselPage.  Since I don't know the intent of the GoBack call, I have to fire the OnNavigatedTo on both Parent and Child.  Does this seem correct behavior to you?

By the way, great find!

**Comment by brianlagunas** [comment] 2017-03-13 16:01
Maybe we only target the Child and not the parent, because in a GoBack operation we are really navigating to the active child.  Is there a scenario where we want both the parent and child to respond in a go back operation?

**Comment by brianlagunas** [comment] 2017-03-13 16:16
I'm going to go with the Child only approach for now.  Currently for modal navigation scenarios we only call it on the child.  I just overlooked this in the non-modal scenario.  SO I will make the two behaviors the same.  Targeting only the child.

**Comment by brianlagunas** [comment] 2017-03-13 16:29
Fixed with PR #980

**Closed by brianlagunas** 2017-03-13 16:29 UTC
Labels: XF

**Comment by dersia** [comment] 2017-04-14 15:20
Hi Brian,

I was just overseeing some PR to see what happens so far on Prism when I came across this issue.

From a logical point of view, I think your initial thought was right to call OnNavigatedTo on both child an parent, since both are going to be displayed. 

But I also see your point in having the same behavior for modal and non-modal, so I was thinking wouldn't make much more sense to change it for both scenarios to call parent and child?

What do you think?

**Comment by brianlagunas** [comment] 2017-04-14 16:47
This is a tough call. For now I have decided to just call OnNavigatedTo on the child.  Do you have an actual use-case for it to be called on the parent too, or is this just more of a "I was thinking" scenario?

**Comment by dersia** [comment] 2017-04-14 17:39
It was more of a I was thinking scenario.

What I was refering to as "being displayed" is acutally a in case of a MultiPage-Scenario, like for MasterDetail, Tabbed etc. it really is a Navigation to both. But this would also mean, that we need to call OnNavigatedTo and OnNavigatingTo for Forward- and Backward-Navigation on both child and parent.

Since there is no actual pressure so far to make a decision (well you made one so far) and this is more like a conpectual and logical thing to think about, I'd suggest to re-open this issue and have a discussion with the prism community.

**Comment by dansiegel** [comment] 2017-04-14 17:56
@dersia to open up OnNavigatedTo on the parent (TabbedPage, MasterDetailPage, NavigationPage) actually would create more problems for developers than it would solve. If you really have a scenario that you need to notify the parent of the updated NavigationParameters it would be best to create an event that you can publish from the child and subscribe to from the parent.

**Comment by dersia** [comment] 2017-04-14 18:07
@dansiegel I agree that Publishing an event would be the best case, but honestly I think this would be in any case the better solution (against the INavigationAware appraoch, pub-sub seems always better to me).

But then again this is my personal approach.

But I'm curious, what problem would that extra call create? As far as I understood this issue, parent was the only one being called before brian's change.

**Comment by dansiegel** [comment] 2017-04-14 18:45
I'm sure we could come up with a laundry list, but suffice it to say that we would change a core behavior in the NavigationService that would be subtle enough that it could introduce a lot of bugs in existing apps that upgrade. Unlike when we introduced OnNavigatingTo where it was a breaking change that forced developers to implement the new method or change INavigationAware to INavigatedAware.

**Comment by dersia** [comment] 2017-04-14 18:50
You are right that this is a change in the behavior and this cloud cause issue and since no one has an issue with this so far, maybe it's good to leave it this way. It really was just something where I was scratching my head over reading brian's comments above. His first approach to call both just made more sense then just calling the child.

Anyhow it'll be interesting to see if this might be an issue in the future for anyone, I think if and when then this will only be an issue for a minority.

**Comment by cpboyd** [comment] 2017-05-18 21:40
@brianlagunas I think I have a decent reason to pass `NavigationParameters` to the `TabbedPage` itself rather than the child `ContentPage`.

The app is connecting to a separate Bluetooth device.  The tabs all correspond to data retrieved from the Bluetooth device.

I launch a modal view to select a paired device or add a new device.

Basically, I'd like to have the ViewModel of the `TabbedPage` handle device changes so that adding/selecting a device to connect to will pass along some `NavigationParameters` related to that device.

**Comment by brianlagunas** [comment] 2017-05-22 17:17
@cpboyd In that case I would use the event aggregator to send a message with the id of the device and then filter your subscribers to only listen for event for the specific device id.

**Comment by cpboyd** [comment] 2017-05-22 17:40
Ah, good point.

I ended up refactoring the handling of device changes into the singleton I'm using to handle Bluetooth communications, reducing the dependence on the `TabbedPage` itself.  In effect, it's similar to the event aggregator since I'm using an Rx observable.

**Comment by ruanpelissoli** [comment] 2017-06-20 14:55
I'm experiencing this same issue on Android. I navigate to a modal page, and when call GoBackAsync passing parameters my parent page OnNavigatedTo don't get called. Already tryied implementing OnNavigatedTo on both parent and child.

Platform: Android API 25
Prism version: 6.3.0.0
Xamarin version: 2.3.4.247

**Comment by brianlagunas** [comment] 2017-06-26 21:27
@ruanpelissoli Can you provide more information about your scenario.  What does you navigation sack look like?  What type of page are you navigating away from, and what kind of page are you navigating to?  There are no known issues regarding INavigationAware and GoBackAsyc.

**Comment by ruanpelissoli** [comment] 2017-06-27 20:11
I have a CarouselPage, with a filter button in navigation bar, when clicked it pops a modal with filter options (ContentPage), I pass this filters as parameters at GoBackAsync of the modal page, my CarouselPage OnNavigatedTo is not fired to get this filters. My VM's inherit from a BaseViewModal that implements INavigationAware and BindableBase.

CarouselPageVM:
```
private async void FilterCommandExecute()
        {
            await _navigationService.NavigateAsync($"NavigationPage/{nameof(FilterPage)}", null, true);
        }

        //Not fired after GoBackAsync
        public async override void OnNavigatedTo(NavigationParameters parameters)
        {
            base.OnNavigatedTo(parameters);
        }
```

FilterPageVM:
```
private async void FilterCommandExecute()
        {
            var filter = new Filter();

            var parameters = new NavigationParameters
            {
                { "filter", filter }
            };

            await _navigationService.GoBackAsync(parameters, true);
        }
```

**Comment by JaccoDieleman** [comment] 2017-08-04 12:10
@brianlagunas I like the current approach by calling the OnNavigatedTo/OnNavigatingTo in the child instead of the parent. Although it meant our application broke when upgrading from 6.2 to 6.3.
We used to handle the navigation in the parent and then call the OnNavigatedTo of the child our selves. Now the child (a Tab in a TabbedPage) can handle that by itself. Excellent!

Our scenario:
We have a tabbed page, each tab contains a list of items to which the user can add one. Adding a new item means navigating to a page which acts as a picker, We navigating back from the "picker page" we pass the id of the picked item in the NavigationParameters. The newly selected item must be reflected in the tab where the users wanted to add the item.

**Comment by l0gaw** [comment] 2018-01-10 21:14
I'm experiencing this same issue , but with Master Detail Page. I navigate to a popup modal page throughout my master page, and when call GoBackAsync passing parameters from my popup modal OnNavigatedTo don't get called on masterpage. How can i solve this?
