### ISSUE TITLE
[Bug] Navigation From TabbedPage

### ISSUE THREAD

**Issue by mhrastegary77** [PrismLibrary/Prism#2600] opened 2021-10-21 05:09 UTC
### Description
Hi i have a tabbed page and removed the Tabbar to create a custom one and wanted to select tabs from buttons inside the TitleView but prism gives me exceptions what ever i do.

### Basic Information
- Version with issue: 8.1.97
- Last known good version: -
- Xamarin.Forms version: 5 SR 6
- IDE: Visual Studio 2019

**Comment by dansiegel** [comment] 2021-10-21 05:26
This sounds like a duplicate of #2576 fixed by #2577. In which case the fix is available to sponsors in the SponsorConnect feed. If you feel this is a different issue let me know. Also be sure you include a sample reproduction when reporting a bug.

**Closed by dansiegel** 2021-10-21 05:26 UTC
Labels: bug, to verify
